const districts = [
  [
    'NICOBARS/NICOBARS',
    'NORTH AND MIDDLE ANDAMAN/NORTH AND MIDDLE ANDAMAN',
    'SOUTH ANDAMANS/SOUTH ANDAMANS'
  ],
  [
    'ANANTAPUR/ANANTAPUR',
    'CHITTOOR/CHITTOOR',
    'EAST GODAVARI/EAST GODAVARI',
    'GUNTUR/GUNTUR',
    'KRISHNA/KRISHNA',
    'KURNOOL/KURNOOL',
    'PRAKASAM/PRAKASAM',
    'SPSR NELLORE/SPSR NELLORE',
    'SRIKAKULAM/SRIKAKULAM',
    'VISAKHAPATANAM/VISAKHAPATANAM',
    'VIZIANAGARAM/VIZIANAGARAM',
    'WEST GODAVARI/పశ్చిమగోదావరి',
    'Y.S.R./'
  ],
  [
    'ANJAW/',
    'CHANGLANG/CHANGLANG',
    'DIBANG VALLEY/DIBANG VALLEY',
    'EAST KAMENG/EAST KAMENG',
    'EAST SIANG/EAST SIANG',
    'KAMLE/KAMLE',
    'KRA DAADI/KRA DAADI',
    'KURUNG KUMEY/KURUNG KUMEY',
    'LOHIT/LOHIT',
    'LONGDING/LONGDING',
    'LOWER DIBANG VALLEY/LOWER DIBANG VALLEY',
    'LOWER SIANG/LOWER SIANG',
    'LOWER SUBANSIRI/LOWER SUBANSIRI',
    'NAMSAI/',
    'PAPUM PARE/PAPUM PARE',
    'SIANG/',
    'TAWANG/TAWANG',
    'TIRAP/TIRAP',
    'UPPER SIANG/UPPER SIANG',
    'UPPER SUBANSIRI/UPPER SUBANSIRI',
    'WEST KAMENG/WEST KAMENG',
    'WEST SIANG/WEST SIANG'
  ],
  [
    'BAKSA/',
    'BARPETA/BARPETA',
    'Biswanath/',
    'BONGAIGAON/BONGAIGAON',
    'CACHAR/CACHAR',
    'CHARAIDEO/',
    'CHIRANG/',
    'DARRANG/DARRANG',
    'DHEMAJI/DHEMAJI',
    'DHUBRI/DHUBURI',
    'DIBRUGARH/DIBRUGARH',
    'DIMA HASAO/DIMA HASAO',
    'GOALPARA/GOALPARA',
    'GOLAGHAT/GOLAGHAT',
    'HAILAKANDI/HAILAKANDI',
    'HOJAI/',
    'JORHAT/JORHAT',
    'KAMRUP/KAMRUP',
    'KAMRUP METRO/KAMRUP MOHANAGAR',
    'KARBI ANGLONG/KARBI ANGLONG',
    'KARIMGANJ/KARIMGANJ',
    'KOKRAJHAR/KOKRAJHAR',
    'LAKHIMPUR/LAKHIMPUR',
    'MAJULI/',
    'MARIGAON/MARIGAON',
    'NAGAON/NAGAON',
    'NALBARI/NALBARI',
    'SIVASAGAR/SIVASAGAR',
    'SONITPUR/SONITPUR',
    'SOUTH SALMARA MANCACHAR/',
    'TINSUKIA/TINSUKIA',
    'UDALGURI/',
    'WEST KARBI ANGLONG/'
  ],
  [
    'ARARIA/अररिया',
    'ARWAL/अरवल',
    'AURANGABAD/औरंगाबाद',
    'BANKA/बांका',
    'BEGUSARAI/बेगूसराय',
    'BHAGALPUR/भागलपुर',
    'BHOJPUR/भोजपुर',
    'BUXAR/बक्सर',
    'DARBHANGA/दरभंगा',
    'GAYA/गया',
    'GOPALGANJ/गोपालगंज',
    'JAMUI/जमुई',
    'JEHANABAD/जहानाबाद',
    'KAIMUR (BHABUA)/कैमूर ( भभुआ )',
    'KATIHAR/कटिहार',
    'KHAGARIA/खगड़िया',
    'KISHANGANJ/किशनगंज',
    'LAKHISARAI/लखीसराय',
    'MADHEPURA/मधेपुरा',
    'MADHUBANI/मधुबनी',
    'MUNGER/मुंगेर',
    'MUZAFFARPUR/मुजफ्फरपुर',
    'NALANDA/नालंदा',
    'NAWADA/नवादा',
    'PASHCHIM CHAMPARAN/पश्चिम चम्पारण',
    'PATNA/पटना',
    'PURBI CHAMPARAN/पूर्वी चंपारण',
    'PURNIA/पूर्णिया',
    'ROHTAS/रोहतास',
    'SAHARSA/सहरसा',
    'SAMASTIPUR/समस्तीपुर',
    'SARAN/सारण',
    'SHEIKHPURA/शेखपुरा',
    'SHEOHAR/शिवहर',
    'SITAMARHI/सीतामढी',
    'SIWAN/सिवान',
    'SUPAUL/सुपौल',
    'VAISHALI/वैशाली'
  ],
  [
    'CHANDIGARH/CHANDIGARH'
  ],
  [
    'BALOD/',
    'BALODA BAZAR/',
    'BALRAMPUR/Balrampur',
    'BASTAR/BASTAR',
    'BEMETARA/',
    'BIJAPUR/',
    'BILASPUR/BILASPUR',
    'DANTEWADA/DANTEWADA',
    'DHAMTARI/DHAMTARI',
    'DURG/DURG',
    'GARIYABAND/',
    'JANJGIR-CHAMPA/JANJGIR-CHAMPA',
    'JASHPUR/JASHPUR',
    'KABIRDHAM/KAWARDHA',
    'KANKER/KANKER',
    'KONDAGAON/KONDAGAON',
    'KORBA/KORBA',
    'KOREA/KOREA',
    'MAHASAMUND/MAHASAMUND',
    'MUNGELI/',
    'NARAYANPUR/',
    'RAIGARH/RAIGARH',
    'RAIPUR/RAIPUR',
    'RAJNANDGAON/RAJNANDGAON',
    'SUKMA/',
    'SURAJPUR/Surajpur',
    'SURGUJA/SURGUJA'
  ],
  [
    'DADRA AND NAGAR HAVELI/DADRA AND NAGAR HAVELI'
  ],
  [
    'DAMAN/DAMAN',
    'DIU/DIU'
  ],
  [
    'CENTRAL/CENTRAL',
    'EAST/EAST',
    'NEW DELHI/NEW DELHI',
    'NORTH/NORTH',
    'NORTH EAST/NORTH EAST',
    'NORTH WEST/NORTH WEST',
    'SHAHDARA/SHAHDARA',
    'SOUTH/SOUTH',
    'South East/SOUTH EAST',
    'SOUTH WEST/SOUTH WEST',
    'WEST/WEST'
  ],
  [
    'NORTH GOA/NORTH GOA',
    'SOUTH GOA/SOUTH GOA'
  ],
  [
    'AHMADABAD/AHMADABAD',
    'AMRELI/AMRELI',
    'ANAND/ANAND',
    'ARVALLI/',
    'BANAS KANTHA/BANAS KANTHA',
    'BHARUCH/BHARUCH',
    'BHAVNAGAR/BHAVNAGAR',
    'BOTAD/BOTAD',
    'CHHOTAUDEPUR/CHHOTAUDEPUR',
    'DANG/DANG',
    'DEVBHUMI DWARKA/DEVBHUMI DWARKA',
    'DOHAD/DOHAD',
    'GANDHINAGAR/GANDHINAGAR',
    'GIR SOMNATH/GIR SOMNATH',
    'JAMNAGAR/JAMNAGAR',
    'JUNAGADH/JUNAGADH',
    'KACHCHH/KACHCHH',
    'KHEDA/KHEDA',
    'MAHESANA/MAHESANA',
    'Mahisagar/àª®àª¹àª¿àª¸àª¾àª—àª°',
    'MORBI/MORBI',
    'NARMADA/NARMADA',
    'NAVSARI/NAVSARI',
    'PANCH MAHALS/PANCH MAHALS',
    'PATAN/PATAN',
    'PORBANDAR/PORBANDAR',
    'RAJKOT/RAJKOT',
    'SABAR KANTHA/SABAR KANTHA',
    'SURAT/SURAT',
    'SURENDRANAGAR/SURENDRANAGAR',
    'TAPI/',
    'VADODARA/VADODARA',
    'VALSAD/VALSAD'
  ],
  [
    'AMBALA/AMBALA',
    'BHIWANI/BHIWANI',
    'CHARKI DADRI/CHARKI DADRI',
    'FARIDABAD/FARIDABAD',
    'FATEHABAD/FATEHABAD',
    'GURUGRAM/GURUGRAM',
    'HISAR/HISAR',
    'JHAJJAR/JHAJJAR',
    'JIND/JIND',
    'KAITHAL/KAITHAL',
    'KARNAL/KARNAL',
    'KURUKSHETRA/KURUKSHETRA',
    'MAHENDRAGARH/MAHENDRAGARH',
    'MEWAT/',
    'PALWAL/',
    'PANCHKULA/PANCHKULA',
    'PANIPAT/PANIPAT',
    'REWARI/REWARI',
    'ROHTAK/ROHTAK',
    'SIRSA/SIRSA',
    'SONIPAT/SONIPAT',
    'YAMUNANAGAR/YAMUNANAGAR'
  ],
  [
    'BILASPUR/BILASPUR',
    'CHAMBA/CHAMBA',
    'HAMIRPUR/HAMIRPUR',
    'KANGRA/KANGRA',
    'KINNAUR/KINNAUR',
    'KULLU/KULLU',
    'LAHUL AND SPITI/LAHUL AND SPITI',
    'MANDI/MANDI',
    'SHIMLA/SHIMLA',
    'SIRMAUR/SIRMAUR',
    'SOLAN/SOLAN',
    'UNA/UNA'
  ],
  [
    'ANANTNAG/ANANTNAG',
    'BADGAM/BADGAM',
    'BANDIPORA/BANDIPORA',
    'BARAMULLA/BARAMULLA',
    'DODA/DODA',
    'GANDERBAL/GANDERBAL',
    'JAMMU/JAMMU',
    'KARGIL/KARGIL',
    'KATHUA/KATHUA',
    'KISHTWAR/',
    'KULGAM/KULGAM',
    'KUPWARA/KUPWARA',
    'LEH LADAKH/LEH LADAKH',
    'POONCH/POONCH',
    'PULWAMA/PULWAMA',
    'RAJAURI/RAJAURI',
    'RAMBAN/RAMBAN',
    'REASI/REASI',
    'SAMBA/SAMBA',
    'SHOPIAN/SHOPIAN',
    'SRINAGAR/SRINAGAR',
    'UDHAMPUR/UDHAMPUR'
  ],
  [
    'BOKARO/BOKARO',
    'CHATRA/CHATRA',
    'DEOGHAR/DEOGHAR',
    'DHANBAD/DHANBAD',
    'DUMKA/DUMKA',
    'EAST SINGHBUM/EAST SINGHBUM',
    'GARHWA/GARHWA',
    'GIRIDIH/GIRIDIH',
    'GODDA/GODDA',
    'GUMLA/GUMLA',
    'HAZARIBAGH/HAZARIBAGH',
    'JAMTARA/JAMTARA',
    'KHUNTI/',
    'KODERMA/KODERMA',
    'LATEHAR/LATEHAR',
    'LOHARDAGA/LOHARDAGA',
    'PAKUR/PAKUR',
    'PALAMU/PALAMU',
    'RAMGARH/',
    'RANCHI/RANCHI',
    'SAHEBGANJ/SAHEBGANJ',
    'SARAIKELA KHARSAWAN/SARAIKELA KHARSAWAN',
    'SIMDEGA/SIMDEGA',
    'WEST SINGHBHUM/WEST SINGHBHUM'
  ],
  [
    'BAGALKOT/BAGALKOT',
    'BALLARI/BALLARI',
    'BELAGAVI/BELAGAVI',
    'BENGALURU RURAL/BENGALURU RURAL',
    'BENGALURU URBAN/BENGALURU URBAN',
    'BIDAR/BIDAR',
    'CHAMARAJANAGAR/CHAMARAJANAGAR',
    'CHIKBALLAPUR/CHIKBALLAPUR',
    'CHIKKAMAGALURU/CHIKKAMAGALURU',
    'CHITRADURGA/CHITRADURGA',
    'DAKSHIN KANNAD/DAKSHIN KANNAD',
    'DAVANGERE/DAVANGERE',
    'DHARWAD/DHARWAD',
    'GADAG/GADAG',
    'HASSAN/HASSAN',
    'HAVERI/HAVERI',
    'KALABURAGI/KALABURAGI',
    'KODAGU/KODAGU',
    'KOLAR/KOLAR',
    'KOPPAL/KOPPAL',
    'MANDYA/MANDYA',
    'MYSURU/MYSURU',
    'RAICHUR/RAICHUR',
    'RAMANAGARA/RAMANAGARA',
    'SHIVAMOGGA/SHIVAMOGGA',
    'TUMAKURU/TUMAKURU',
    'UDUPI/UDUPI',
    'UTTAR KANNAD/UTTAR KANNAD',
    'VIJAYAPURA/VIJAYAPURA',
    'YADGIR/'
  ],
  [
    'ALAPPUZHA/ALAPPUZHA',
    'ERNAKULAM/ERNAKULAM',
    'IDUKKI/IDUKKI',
    'KANNUR/KANNUR',
    'KASARAGOD/KASARAGOD',
    'KOLLAM/KOLLAM',
    'KOTTAYAM/KOTTAYAM',
    'KOZHIKODE/KOZHIKODE',
    'MALAPPURAM/MALAPPURAM',
    'PALAKKAD/PALAKKAD',
    'PATHANAMTHITTA/PATHANAMTHITTA',
    'THIRUVANANTHAPURAM/THIRUVANANTHAPURAM',
    'THRISSUR/THRISSUR',
    'WAYANAD/WAYANAD'
  ],
  [
    'LAKSHADWEEP DISTRICT/LAKSHADWEEP DISTRICT'
  ],
  [
    'AGAR MALWA/AGAR MALWA',
    'ALIRAJPUR/ALIRAJPUR',
    'ANUPPUR/ANUPPUR',
    'ASHOKNAGAR/ASHOKNAGAR',
    'BALAGHAT/BALAGHAT',
    'BARWANI/BARWANI',
    'BETUL/BETUL',
    'BHIND/BHIND',
    'BHOPAL/BHOPAL',
    'BURHANPUR/BURHANPUR',
    'CHHATARPUR/CHHATARPUR',
    'CHHINDWARA/CHHINDWARA',
    'DAMOH/DAMOH',
    'DATIA/DATIA',
    'DEWAS/DEWAS',
    'DHAR/DHAR',
    'DINDORI/DINDORI',
    'EAST NIMAR/EAST NIMAR',
    'GUNA/GUNA',
    'GWALIOR/GWALIOR',
    'HARDA/HARDA',
    'HOSHANGABAD/HOSHANGABAD',
    'INDORE/INDORE',
    'JABALPUR/JABALPUR',
    'JHABUA/JHABUA',
    'KATNI/KATNI',
    'KHARGONE/KHARGONE',
    'MANDLA/MANDLA',
    'MANDSAUR/MANDSAUR',
    'MORENA/MORENA',
    'NARSINGHPUR/NARSINGHPUR',
    'NEEMUCH/NEEMUCH',
    'PANNA/PANNA',
    'RAISEN/RAISEN',
    'RAJGARH/RAJGARH',
    'RATLAM/RATLAM',
    'REWA/REWA',
    'SAGAR/SAGAR',
    'SATNA/SATNA',
    'SEHORE/SEHORE',
    'SEONI/SEONI',
    'SHAHDOL/SHAHDOL',
    'SHAJAPUR/SHAJAPUR',
    'SHEOPUR/SHEOPUR',
    'SHIVPURI/SHIVPURI',
    'SIDHI/SIDHI',
    'SINGRAULI/SINGRAULI',
    'TIKAMGARH/TIKAMGARH',
    'UJJAIN/UJJAIN',
    'UMARIA/UMARIA',
    'VIDISHA/VIDISHA'
  ],
  [
    'AHMEDNAGAR/AHMEDNAGAR',
    'AKOLA/AKOLA',
    'AMRAVATI/AMRAVATI',
    'AURANGABAD/AURANGABAD',
    'BEED/BEED',
    'BHANDARA/BHANDARA',
    'BULDHANA/BULDHANA',
    'CHANDRAPUR/CHANDRAPUR',
    'DHULE/DHULE',
    'GADCHIROLI/GADCHIROLI',
    'GONDIA/GONDIA',
    'HINGOLI/HINGOLI',
    'JALGAON/जळगाव',
    'JALNA/JALNA',
    'KOLHAPUR/KOLHAPUR',
    'LATUR/LATUR',
    'MUMBAI/MUMBAI',
    'MUMBAI SUBURBAN/MUMBAI SUBURBAN',
    'NAGPUR/NAGPUR',
    'NANDED/NANDED',
    'NANDURBAR/NANDURBAR',
    'NASHIK/NASHIK',
    'OSMANABAD/OSMANABAD',
    'PALGHAR/पालघर',
    'PARBHANI/PARBHANI',
    'PUNE/PUNE',
    'RAIGAD/RAIGAD',
    'RATNAGIRI/RATNAGIRI',
    'SANGLI/SANGLI',
    'SATARA/SATARA',
    'SINDHUDURG/SINDHUDURG',
    'SOLAPUR/SOLAPUR',
    'THANE/ठाणे',
    'WARDHA/WARDHA',
    'WASHIM/WASHIM',
    'YAVATMAL/YAVATMAL'
  ],
  [
    'BISHNUPUR/BISHNUPUR',
    'CHANDEL/CHANDEL',
    'CHURACHANDPUR/CHURACHANDPUR',
    'IMPHAL EAST/IMPHAL EAST',
    'IMPHAL WEST/IMPHAL WEST',
    'JIRIBAM/',
    'KAKCHING/',
    'KAMJONG/',
    'KANGPOKPI/',
    'NONEY/NONEY',
    'PHERZAWL/',
    'SENAPATI/SENAPATI',
    'TAMENGLONG/TAMENGLONG',
    'TENGNOUPAL/TENGNOUPAL',
    'THOUBAL/THOUBAL',
    'UKHRUL/UKHRUL'
  ],
  [
    'EAST GARO HILLS/EAST GARO HILLS',
    'EAST JAINTIA HILLS/EAST JAINTIA HILLS',
    'EAST KHASI HILLS/EAST KHASI HILLS',
    'NORTH GARO HILLS/NORTH GARO HILLS',
    'RI BHOI/RI BHOI',
    'SOUTH GARO HILLS/SOUTH GARO HILLS',
    'SOUTH WEST GARO HILLS/SOUTH WEST GARO HILLS',
    'SOUTH WEST KHASI HILLS/SOUTH WEST KHASI HILLS',
    'WEST GARO HILLS/WEST GARO HILLS',
    'WEST JAINTIA HILLS/WEST JAINTIA HILLS',
    'WEST KHASI HILLS/WEST KHASI HILLS'
  ],
  [
    'AIZAWL/AIZAWL',
    'CHAMPHAI/CHAMPHAI',
    'KOLASIB/KOLASIB',
    'LAWNGTLAI/LAWNGTLAI',
    'LUNGLEI/LUNGLEI',
    'MAMIT/MAMIT',
    'SAIHA/SAIHA',
    'SERCHHIP/SERCHHIP'
  ],
  [
    'DIMAPUR/DIMAPUR',
    'KIPHIRE/',
    'KOHIMA/KOHIMA',
    'LONGLENG/',
    'MOKOKCHUNG/MOKOKCHUNG',
    'MON/MON',
    'PEREN/',
    'PHEK/PHEK',
    'TUENSANG/TUENSANG',
    'WOKHA/WOKHA',
    'ZUNHEBOTO/ZUNHEBOTO'
  ],
  [
    'ANUGUL/ANUGUL',
    'BALANGIR/BALANGIR',
    'BALESHWAR/BALESHWAR',
    'BARGARH/BARGARH',
    'BHADRAK/BHADRAK',
    'BOUDH/BOUDH',
    'CUTTACK/CUTTACK',
    'DEOGARH/DEOGARH',
    'DHENKANAL/DHENKANAL',
    'GAJAPATI/GAJAPATI',
    'GANJAM/GANJAM',
    'JAGATSINGHAPUR/JAGATSINGHAPUR',
    'JAJAPUR/JAJAPUR',
    'JHARSUGUDA/JHARSUGUDA',
    'KALAHANDI/KALAHANDI',
    'KANDHAMAL/KANDHAMAL',
    'KENDRAPARA/KENDRAPARA',
    'KENDUJHAR/KENDUJHAR',
    'KHORDHA/KHORDHA',
    'KORAPUT/KORAPUT',
    'MALKANGIRI/MALKANGIRI',
    'MAYURBHANJ/MAYURBHANJ',
    'NABARANGPUR/NABARANGPUR',
    'NAYAGARH/NAYAGARH',
    'NUAPADA/NUAPADA',
    'PURI/PURI',
    'RAYAGADA/RAYAGADA',
    'SAMBALPUR/SAMBALPUR',
    'SONEPUR/SONEPUR',
    'SUNDARGARH/SUNDARGARH'
  ],
  [
    'KARAIKAL/KARAIKAL',
    'MAHE/MAHE',
    'PONDICHERRY/PONDICHERRY',
    'YANAM/YANAM'
  ],
  [
    'AMRITSAR/AMRITSAR',
    'BARNALA/',
    'BATHINDA/BATHINDA',
    'FARIDKOT/FARIDKOT',
    'FATEHGARH SAHIB/FATEHGARH SAHIB',
    'FAZILKA/',
    'FIROZEPUR/FIROZEPUR',
    'GURDASPUR/GURDASPUR',
    'HOSHIARPUR/HOSHIARPUR',
    'JALANDHAR/JALANDHAR',
    'KAPURTHALA/KAPURTHALA',
    'LUDHIANA/ਲੂਿਧਆਣਾ',
    'MANSA/ਮਾਨਸਾ',
    'MOGA/MOGA',
    'PATHANKOT/PATHANKOT',
    'PATIALA/PATIALA',
    'RUPNAGAR/RUPNAGAR',
    'SANGRUR/SANGRUR',
    'S.A.S Nagar/',
    'Shahid Bhagat Singh Nagar/Shahid Bhagat Singh Nagar',
    'SRI MUKTSAR SAHIB/ਸ੍ਰੀ ਮੁਕਤਸਰ ਸਾਹਿਬ',
    'Tarn Taran/tarn taran'
  ],
  [
    'AJMER/AJMER',
    'ALWAR/ALWAR',
    'BANSWARA/BANSWARA',
    'BARAN/BARAN',
    'BARMER/BARMER',
    'BHARATPUR/BHARATPUR',
    'BHILWARA/BHILWARA',
    'BIKANER/BIKANER',
    'BUNDI/BUNDI',
    'CHITTORGARH/CHITTORGARH',
    'CHURU/CHURU',
    'DAUSA/DAUSA',
    'DHOLPUR/DHOLPUR',
    'DUNGARPUR/DUNGARPUR',
    'GANGANAGAR/GANGANAGAR',
    'HANUMANGARH/HANUMANGARH',
    'JAIPUR/JAIPUR',
    'JAISALMER/JAISALMER',
    'JALORE/JALORE',
    'JHALAWAR/JHALAWAR',
    'JHUNJHUNU/JHUNJHUNU',
    'JODHPUR/JODHPUR',
    'KARAULI/KARAULI',
    'KOTA/KOTA',
    'NAGAUR/NAGAUR',
    'PALI/PALI',
    'PRATAPGARH/',
    'RAJSAMAND/RAJSAMAND',
    'SAWAI MADHOPUR/SAWAI MADHOPUR',
    'SIKAR/SIKAR',
    'SIROHI/SIROHI',
    'TONK/TONK',
    'UDAIPUR/UDAIPUR'
  ],
  [
    'EAST DISTRICT/EAST DISTRICT',
    'NORTH DISTRICT/NORTH DISTRICT',
    'SOUTH DISTRICT/SOUTH DISTRICT',
    'WEST DISTRICT/WEST DISTRICT'
  ],
  [
    'Ariyalur/',
    'CHENNAI/CHENNAI',
    'COIMBATORE/COIMBATORE',
    'CUDDALORE/CUDDALORE',
    'DHARMAPURI/DHARMAPURI',
    'DINDIGUL/DINDIGUL',
    'ERODE/ERODE',
    'KANCHIPURAM/KANCHIPURAM',
    'KANNIYAKUMARI/KANNIYAKUMARI',
    'KARUR/KARUR',
    'KRISHNAGIRI/KRISHNAGIRI',
    'MADURAI/MADURAI',
    'NAGAPATTINAM/NAGAPATTINAM',
    'NAMAKKAL/NAMAKKAL',
    'PERAMBALUR/PERAMBALUR',
    'PUDUKKOTTAI/PUDUKKOTTAI',
    'RAMANATHAPURAM/RAMANATHAPURAM',
    'SALEM/SALEM',
    'SIVAGANGA/SIVAGANGA',
    'THANJAVUR/THANJAVUR',
    'THENI/THENI',
    'THE NILGIRIS/THE NILGIRIS',
    'THIRUVALLUR/THIRUVALLUR',
    'THIRUVARUR/THIRUVARUR',
    'TIRUCHIRAPPALLI/TIRUCHIRAPPALLI',
    'TIRUNELVELI/TIRUNELVELI',
    'TIRUPPUR/TIRUPPUR',
    'TIRUVANNAMALAI/TIRUVANNAMALAI',
    'TUTICORIN/TUTICORIN',
    'VELLORE/VELLORE',
    'VILLUPURAM/VILLUPURAM',
    'VIRUDHUNAGAR/VIRUDHUNAGAR'
  ],
  [
    'ADILABAD/ఆదిలాబాద్',
    'BHADRADRI KOTHAGUDEM/భద్రాద్రి కొత్తగూడెం',
    'HYDERABAD/HYDERABAD',
    'Jagitial/Jagitial',
    'JANGOAN/JANGOAN',
    'JAYASHANKAR BHUPALAPALLY/జయశంకర్ భూపాలపల్లి',
    'JOGULAMBA GADWAL/జోగులాంబ గద్వాల',
    'KAMAREDDY/KAMAREDDY',
    'KARIMNAGAR/కరీంనగర్',
    'KHAMMAM/KHAMMAM',
    'KUMURAM BHEEM ASIFABAD/కుమురం భీమ్ ఆసిఫాబాద్',
    'MAHABUBABAD/MAHABUBABAD',
    'MAHABUBNAGAR/మహబూబ్ నగర్',
    'MANCHERIAL/MANCHERIAL',
    'MEDAK/MEDAK',
    'MEDCHAL MALKAJGIRI/మేడ్చల్ మల్కాజిగిరి',
    'NAGARKURNOOL/NAGARKURNOOL',
    'NALGONDA/NALGONDA',
    'Nirmal/Nirmal',
    'NIZAMABAD/NIZAMABAD',
    'PEDDAPALLI/PEDDAPALLI',
    'RAJANNA SIRCILLA/రాజన్న సిరిసిల్ల',
    'RANGA REDDY/రంగా రెడ్డి',
    'SANGAREDDY/SANGAREDDY',
    'SIDDIPET/SIDDIPET',
    'SURYAPET/SURYAPET',
    'VIKARABAD/VIKARABAD',
    'WANAPARTHY/WANAPARTHY',
    'WARANGAL RURAL/WARANGAL RURAL',
    'WARANGAL URBAN/WARANGAL URBAN',
    'YADADRI BHUVANAGIRI/యదాద్రి భువనగిరి'
  ],
  [
    'Dhalai/DHALAI',
    'Gomati/GOMATI',
    'Khowai/KHOWAI',
    'North Tripura/NORTH TRIPURA',
    'Sepahijala/SEPAHIJALA',
    'South Tripura/SOUTH TRIPURA',
    'Unakoti/UNAKOTI',
    'West Tripura/WEST TRIPURA'
  ],
  [
    'ALMORA/ALMORA',
    'BAGESHWAR/BAGESHWAR',
    'CHAMOLI/CHAMOLI',
    'CHAMPAWAT/CHAMPAWAT',
    'DEHRADUN/DEHRADUN',
    'HARIDWAR/HARIDWAR',
    'NAINITAL/NAINITAL',
    'PAURI GARHWAL/PAURI GARHWAL',
    'PITHORAGARH/PITHORAGARH',
    'RUDRA PRAYAG/RUDRA PRAYAG',
    'TEHRI GARHWAL/TEHRI GARHWAL',
    'UDAM SINGH NAGAR/UDAM SINGH NAGAR',
    'UTTAR KASHI/UTTAR KASHI'
  ],
  [
    'AGRA/AGRA',
    'ALIGARH/ALIGARH',
    'ALLAHABAD/ALLAHABAD',
    'AMBEDKAR NAGAR/AMBEDKAR NAGAR',
    'Amethi/Amethi',
    'AMROHA/AMROHA',
    'AURAIYA/AURAIYA',
    'AZAMGARH/AZAMGARH',
    'BAGHPAT/BAGHPAT',
    'BAHRAICH/BAHRAICH',
    'BALLIA/BALLIA',
    'BALRAMPUR/BALRAMPUR',
    'BANDA/BANDA',
    'BARABANKI/BARABANKI',
    'BAREILLY/BAREILLY',
    'BASTI/BASTI',
    'BHADOHI/BHADOHI',
    'BIJNOR/BIJNOR',
    'BUDAUN/BUDAUN',
    'BULANDSHAHR/BULANDSHAHR',
    'CHANDAULI/CHANDAULI',
    'CHITRAKOOT/CHITRAKOOT',
    'DEORIA/DEORIA',
    'ETAH/ETAH',
    'ETAWAH/ETAWAH',
    'FAIZABAD/FAIZABAD',
    'FARRUKHABAD/FARRUKHABAD',
    'FATEHPUR/FATEHPUR',
    'FIROZABAD/FIROZABAD',
    'GAUTAM BUDDHA NAGAR/GAUTAM BUDDHA NAGAR',
    'GHAZIABAD/GHAZIABAD',
    'GHAZIPUR/GHAZIPUR',
    'GONDA/GONDA',
    'GORAKHPUR/GORAKHPUR',
    'HAMIRPUR/HAMIRPUR',
    'HAPUR/HAPUR',
    'HARDOI/HARDOI',
    'HATHRAS/HATHRAS',
    'JALAUN/JALAUN',
    'JAUNPUR/JAUNPUR',
    'JHANSI/JHANSI',
    'KANNAUJ/KANNAUJ',
    'KANPUR DEHAT/KANPUR DEHAT',
    'KANPUR NAGAR/KANPUR NAGAR',
    'Kasganj/Kasganj',
    'KAUSHAMBI/KAUSHAMBI',
    'KHERI/KHERI',
    'KUSHI NAGAR/KUSHI NAGAR',
    'LALITPUR/LALITPUR',
    'LUCKNOW/LUCKNOW',
    'MAHARAJGANJ/MAHARAJGANJ',
    'MAHOBA/MAHOBA',
    'MAINPURI/MAINPURI',
    'MATHURA/MATHURA',
    'MAU/MAU',
    'MEERUT/MEERUT',
    'MIRZAPUR/MIRZAPUR',
    'MORADABAD/MORADABAD',
    'MUZAFFARNAGAR/MUZAFFARNAGAR',
    'PILIBHIT/PILIBHIT',
    'PRATAPGARH/PRATAPGARH',
    'RAE BARELI/RAE BARELI',
    'RAMPUR/RAMPUR',
    'SAHARANPUR/SAHARANPUR',
    'SAMBHAL/SAMBHAL',
    'SANT KABEER NAGAR/SANT KABEER NAGAR',
    'SHAHJAHANPUR/SHAHJAHANPUR',
    'SHAMLI/SHAMLI',
    'SHRAVASTI/SHRAVASTI',
    'SIDDHARTH NAGAR/SIDDHARTH NAGAR',
    'SITAPUR/SITAPUR',
    'SONBHADRA/SONBHADRA',
    'SULTANPUR/SULTANPUR',
    'UNNAO/UNNAO',
    'VARANASI/VARANASI'
  ],
  [
    '24 PARAGANAS NORTH/24 PARAGANAS NORTH',
    '24 PARAGANAS SOUTH/24 PARAGANAS SOUTH',
    'Alipurduar/',
    'BANKURA/BANKURA',
    'BIRBHUM/BIRBHUM',
    'COOCHBEHAR/COOCHBEHAR',
    'DARJEELING/DARJEELING',
    'DINAJPUR DAKSHIN/DINAJPUR DAKSHIN',
    'DINAJPUR UTTAR/DINAJPUR UTTAR',
    'HOOGHLY/HOOGHLY',
    'HOWRAH/HOWRAH',
    'JALPAIGURI/JALPAIGURI',
    'Jhargram/Jhargram',
    'KALIMPONG/KALIMPONG',
    'KOLKATA/KOLKATA',
    'MALDAH/MALDAH',
    'MEDINIPUR EAST/MEDINIPUR EAST',
    'MEDINIPUR WEST/MEDINIPUR WEST',
    'MURSHIDABAD/MURSHIDABAD',
    'NADIA/NADIA',
    'PASCHIM BARDHAMAN/PASCHIM BARDHAMAN',
    'PURBA BARDHAMAN/PURBA BARDHAMAN',
    'PURULIA/PURULIA'
  ]
];

const subDivisions = {
  4: [
    [
      "ARARIA/अररिया",
      "FORBESGANJ/फोरबिसगंज"
    ],
    [
      "ARWAL/अरवल"
    ],
    [
      "AURANGABAD/औरंगाबाद",
      "DAUDNAGAR/दाऊद नगर"
    ],
    [
      "BANKA/बाँका"
    ],
    [
      "BAKHRI/बखरी",
      "BALIA/बलिया",
      "BEGUSARAI/बेगूसराय",
      "MANJHAUL/मंझौल",
      "TEGHRA/तेघरा"
    ],
    [
      "BHAGALPUR/भागलपुर",
      "KAHALGAON/कहलगाँव",
      "NAVGACHHIYA/नवगछिया"
    ],
    [
      "ARA/आरा",
      "JAGDISHPUR/जगदीशपुर",
      "PIRO/पिरो"
    ],
    [
      "BUXAR/बक्सर",
      "DUMRAON/डुमरांव"
    ],
    [
      "BENIPUR/बेनीपुर",
      "BIRAUL/बिरौल",
      "DARBHANGA/दरभंगा सदर"
    ],
    [
      "GAYA SADAR/गया सदर",
      "NEEMCHAK BATHANI/नीमचक बथानी",
      "SHERGHATTY/शेरघाटी",
      "TEKARI/टेकारी"
    ],
    [
      "GOPALGANJ/गोपालगंज",
      "HATHUA/हथुआ"
    ],
    [
      "JAMUI/जमुई"
    ],
    [
      "JEHANABAD/जहानाबाद"
    ],
    [
      "BHABHUA/भभुआ",
      "MOHANIA/मोहनियॉं"
    ],
    [
      "BARSOI/बारसोई",
      "KATIHAR/कटिहार",
      "MANIHARI/मनीहारी"
    ],
    [
      "GOGRI/गोगरी",
      "KHAGARIA/खगड़िया"
    ],
    [
      "KISHANGANJ/किशनगंज"
    ],
    [
      "LAKHISARAI/लखीसराय"
    ],
    [
      "MADHEPURA/मधेपुरा",
      "UDAKISHUNGANJ/उदाकिशनगंज"
    ],
    [
      "BENIPATTI/बेनीपट्टी",
      "JAYNAGAR/जयनगर",
      "JHANJHARPUR/झंझारपुर",
      "MADHUBANI/मधुबनी",
      "PHULPARAS/फूलपारस"
    ],
    [
      "HAWELI KHARAGPUR/हवेली खड़गपुर",
      "MUNGER SADAR/मुंगेर सदर",
      "TARAPUR/तारापुर"
    ],
    [
      "MUZAFFARPUR   EAST/मुजफ्फरपुर(पूर्वी)",
      "MUZAFFARPUR  WEST/मुजफ्फरपुर(पश्चिमी)"
    ],
    [
      "BIHARSHARIF/बिहारशरीफ़",
      "HILSA/हिलसा",
      "RAJGIR/राजगीर"
    ],
    [
      "NAWADA/नवादा",
      "RAJAULI/रजौली"
    ],
    [
      "BAGAHA/बगहा",
      "BETTIAH/बेत्तिया",
      "NARKATIYAGANJ/नरकटियागंज"
    ],
    [
      "BARH/बाढ़",
      "Danapur/दानापुर",
      "MASAURHI/मसौढ़ी",
      "PALIGANJ/पालीगंज",
      "PATNA CITY/पटना सिटी",
      "PATNA SADAR/पटना सदर"
    ],
    [
      "ARERAJ/अरेराज",
      "CHAKIYA/चकिया",
      "MOTIHARI/मोतीहारी",
      "PAKARIDYAL/पकड़ीदयाल",
      "RAXAUL/रक्सौल",
      "SIKARHANA/सिकरहना"
    ],
    [
      "BAISI/बायसी ",
      "BANMANKHI/बनमंखी",
      "DHAMDAHA/धमदाहा",
      "Others/अन्य",
      "PURNIA SADAR/पूर्णिया सदर"
    ],
    [
      "BIKRAMGANJ/बिक्रमगंज",
      "DEHRI/डेहरी",
      "SASARAM/सासाराम"
    ],
    [
      "SAHARSA/सहरसा",
      "SIMRI BAKHTIARPUR/सिमरी बख्तियारपुर"
    ],
    [
      "DALSINGHSARAI/दलसिंह सराय",
      "PATORI/पटोरी",
      "ROSERA/रोसड़ा",
      "SAMASTIPUR SADAR/समस्तीपुर सदर"
    ],
    [
      "MARHAURA/मढ़ौरा",
      "SARAN SADAR/सारण सदर",
      "SONEPUR/सोनपुर"
    ],
    [
      "SHEIKHPURA/शेखपुरा"
    ],
    [
      "SHEOHAR/शिवहर"
    ],
    [
      "BELSAND/बेलसंड",
      "PUPRI/पूपरी",
      "SITAMARHI SADAR/सीतामढ़ी सदर"
    ],
    [
      "MAHARAJGANJ/महाराजगंज",
      "SIWAN SADAR/सीवान सदर"
    ],
    [
      "BIRPUR/बीरपुर",
      "NIRMALI/निर्मली",
      "SUPAUL/सुपौल",
      "TRIVENIGANJ/त्रिवेणीगंज"
    ],
    [
      "HAJIPUR/हाजीपुर",
      "MAHNAR/महनार",
      "MAHUA/महुआ"
    ]
  ]
};

const policeStations = {
  4: [
    [
      'ARARIA/अररिया',
      'BAIRGACHI O P/बैरगाछी',
      'BARDAHA/बरदाहा ',
      'BASMATIA O P/बसमतिया ओ पी',
      'BATHNAHA O P/बथनाहा',
      'BHARGAMA/भरगावॉ',
      'BOUNSI/बौंसी',
      'FORBESGANJ/फारबीसगंज',
      'FULKAHA/फुलकाहा',
      'GHURNA/घुरना',
      'JOGBANI/जोगबनी',
      'JOKIHAT/जौकीहाट',
      'KUARI O P/कुआरी',
      'KURSAKANTA/कुर्साकांटा',
      'MADANPUR O P/मदनपुर',
      'MAHALGAON/महलगांव',
      'NARPATGANJ/नरपतगंज',
      'PALASI/पलासी',
      'RANIGANJ/रानीगंज',
      'R S O P/आर एस ओ पी',
      'SIKTI/सिकटी',
      'SIMRAHA/सिमराहा',
      'SONMANI GODAM/सोनमणि गोदाम',
      'TARABARI/ताराबरी'
    ],
    [
      'Arwal/अरवल',
      'Banshi/बंशी',
      'Kaler/कलेर',
      'Karpi/करपी',
      'Kinjer/किंजर',
      'Kurtha/कुर्था',
      'Manikpur/मानिकपुर',
      'Mehandiya/मेहन्दिया',
      'Parasi/परासी',
      'Rampur Chauram/रामपुर चौरम',
      'Saher Telpa/शहर तेलपा'
    ],
    [
      'Amba Police Station/अम्बा थाना',
      'Aurangabad Mufassil Police Station/औरंगाबाद मुफ्फसिल थाना',
      'Badem OP/बडेम ओ0 पी0',
      'Bandey Police Station/बंदेया',
      'Barun Police Station/बारुण थाना',
      'Daudnagar Police Station/दाउदनगर थाना',
      'Devkund Police Station/देवकुण्ड थाना',
      'Dev Police Station/देव थाना',
      'Dhibra Police Station/ढ़िबरा थाना',
      'Feser Police Station/फेसर थाना',
      'Goh Police Station/गोह थाना',
      'Haspura Police Station/हसपुरा थाना',
      'Jamhor Police Station/जम्होर थाना',
      'Kasma Police Station/कसमा थाना',
      'Khudwan Police Station/खुदवॉ थाना',
      'Kutumba Police Station/कुटुम्बा थाना',
      'Madanpur Police Station/मदनपुर थाना',
      'Mali Police Station/माली थाना',
      'Nabinagar Police Station/नबीनगर थाना',
      'Narari Kala Khurd Police Station/नरारी कला खुर्द थाना',
      'NTPC khaira Police Station/एन०टी०पी०सी० खैरा थाना',
      'Obra Police Station/ओबरा थाना',
      'Pauthu Police Station/पौथु थाना',
      'Rafiganj Police Station/रफीगंज थाना',
      'Risiyap Police Station/रिसीयप थाना',
      'Salaiya Police Station/सलैया थाना',
      'Simra Police Station/सिमरा थाना',
      'Tandwa Police Station/टण्डवा थाना',
      'Town Police Station/टाउन थाना',
      'Uphara Police Station/उपहरा थाना'
    ],
    [
      'Amarpur Thana/अमरपुर थाना',
      'Anandpur OP/आनन्दपुर ओ0पी0',
      'Bandhuwa kurawa OP/बंधुआकुरांव ओ0पी0',
      'Banka Thana/बांका थाना',
      'Barahat Thana/बाराहाट थाना',
      'Belhar Thana/बेलहर थाना',
      'Bounsi Thana/वौसी थाना',
      'Chandan Thana/चांदन थाना',
      'Dhankund Thana/धनकुंड थाना',
      'Dhoraiya Thana/धोरैया थाना',
      'Fullidumar OP/फुल्लीडुमर ओ0पी0',
      'Jaypur Thana/जयपुर थाना',
      'Katoriya Thana/कटोरिया थाना',
      'khesar OP/खेसर ओ0पी0',
      'Nawada Bajar OP/नवादा बाजार ओ0पी0',
      'Panjwara OP/पंजवाड़ा थाना',
      'Rajoun/रजौन थाना',
      'Shambhuganj Thana/शंभुगंज थाना',
      'Suiya OP/सुईया थाना'
    ],
    [
      'BACHAWARA PS/बछवाड़ा थाना',
      'BAKHARI PS/बखरी थाना',
      'BALIA PS/बलिया थाना',
      'BARAUNI PS/बरौनी थाना',
      'BEGUSARAI TOWN PS/नगर थाना',
      'BHGAWANPUR PS/भगवानपुर थाना',
      'BIRPUR PS/वीरपुर थाना',
      'CHAKIA OP/चकिया ओपी',
      'CHERIYABARIYARPUR PS/चेरियाबरियारपुर थाना',
      'CHHAURAHI OP/छौड़ाही ओपी',
      'DANDARI PS/डंडारी थाना',
      'F C I OP/एफ.सी.आई ओपी',
      'FULAWARIYA PS/फुलवरिया थाना',
      'GARAHRA OP/गड़हरा ओपी',
      'GARHPURA PS/गढपुरा थाना',
      'KHODAWANDPUR PS/खोदाबंदपुर थाना',
      'LAKHO OP/लाखो ओपी',
      'LOHIYANAGAR OP/लोहियानगर ओपी',
      'MANJHAUL OP/मंझौल ओपी',
      'MANSOORCHAK PS/मंसूरचक थाना',
      'MATIHANI PS/मटिहानी थाना',
      'MUFFASIL PS/मुफसिल थाना',
      'NAWAKOTHI PS/नावकोठी थाना',
      'NAYAGAON PS/नयागांव थाना',
      'NIMACHANDPURA PS/नीमाचाँदपुरा थाना',
      'PARIHARA OP/परिहारा ओपी',
      'RATANPUR OP/रतनपुर ओपी',
      'REFINARY OP/रिफाइनरी ओपी',
      'SAHEBPUR KAMAL PS/साहेबपुरकमाल थाना',
      'SAMHO AKHA KURHA PS/शाम्हो अकहा कुरहा थाना',
      'SINGHAUL OP/सिंघौल ओपी',
      'TEGHRA PS/तेघरा थाना',
      'TIYAY OP/तियाय ओपी',
      'ZEROMILE OP/जीरोमाईल ओपी'
    ],
    [
      'AKBARNAGAR/अकबर नगर',
      'AMDANDA/अमडण्डा',
      'ANTICHAK/अंतीचक',
      'BABARGAJ/बबरगंज',
      'BAIPASS/बाईपास',
      'BAKHARPUR/बाखरपुर',
      'BARARI/बरारी',
      'BATH/बाथ',
      'BHAWANIPUR OP/भवानीपुर',
      'BIHPUR/बिहपुर',
      'BUDDHUCHAK/बुद्धुचक',
      'DHOLABAJJA/ढोलबजा',
      'EKCHARI/एकचारी',
      'GHOGHA/घोघा',
      'GOPALPUR/गोपालपुर',
      'GORADIH/गोराडीह',
      'HABIBPUR/हबीबपुर',
      'INDUSTRIAL/औद्योगिक ',
      'ISHAKCHAK/इसाकचक',
      'ISHIPUR/इसीपुर',
      'ISMAILPUR/इस्माइलपुर',
      'JAGDISHPUR/जगदीशपुर',
      'JHANDAPUR OP/झंडापुर',
      'JOGSAR/जोगसर',
      'KADWA OP/कदवा',
      'KAHALGAON/कहलगॉव',
      'KAJRAILY/कजरैली',
      'KHARIK/खरीक',
      'KOTWALI/कोतवाली',
      'LALMATIA/ललमटिया',
      'LODIPUR/लोदीपुर',
      'MADHUSUDANPUR/मधुसूदनपुर',
      'MOJAHIDPUR/मोजाहिदपुर',
      'NADI THANA/नदी थाना',
      'NATHNAGAR/नाथनगर',
      'NAUGACHIA/नवगछिया',
      'NTPC/एन०टी०पी०सी०',
      'PARBATTA/परबता',
      'PIRPAITY/पीरपैंती',
      'RANGRA OP/रंगरा',
      'RASALPUR/रसलपुर',
      'SABOUR/सबौर',
      'SAJOUR/सजौर',
      'SANHAULA/सन्हौला',
      'SANOKHAR/सनोखर',
      'SHAHKUND/शाहकुण्ड ',
      'SHIVNARAYANPUR/शिवनारायणपुर',
      'SULTANGANJ/सुल्तानगंज',
      'TATARPUR/ततारपुर',
      'TILKAMANJHI/तिलकामॉझी',
      'UNIVERSITY/विश्वविद्यालय'
    ],
    [
      'Agiaon Bazar/अगिआंव बाजार',
      'Agiyao Garhani/अगिआंव (गड़हनी)',
      'Ara Muffasil/आरा मुफ्फसिल',
      'Ara Nawada/आरा नवादा',
      'Ara Town/आरा नगर',
      'Ayar/आयर',
      'Azimabad/अजिमाबाद',
      'Babura/बबुरा',
      'Bahoranpur/बहोरनपुर',
      'Barahara/बड़हरा',
      'Bihiya/बिहियॉ',
      'Chandi/चांदी',
      'Charpokhari/चरपोखरी',
      'Chauri/चौरी',
      'Dhangai/धनगाई',
      'Dhobaha/धोबहाँ',
      'Gajrajganj OP/गजराजगंज ओ0पी0',
      'Gidha/गीधा',
      'Hasanbazar OP/हसन बाजार ओ0पी0',
      'Imadpur/ईमादपुर',
      'Jagdishpur/जगदीशपुर ',
      'Karnamepur/करनामेपुर',
      'Khawaspur/ख्वासपुर',
      'koilawar/कोईलवर',
      'Krishangarh/कृष्णागढ़',
      'Naryanpur/नारायणपुर',
      'Pawana/पवना',
      'Piro/पीरो',
      'Sahaar/सहार',
      'Sandesh/संदेस',
      'Shahpur/शाहपुर',
      'Sikarhatta/सिकरहट्टा',
      'Sinha/सिन्हा',
      'Tarari/तरारी',
      'Tiyar/तीयर',
      'Udwant nagar/उदवंतनगर'
    ],
    [
      'Bagengola/बगेनगोला',
      'Basudeva OP/बासुदेवा ओ0पी0',
      'Brahmpur/ब्रहमपुर',
      'Chakki OP Brahmpur/चक्की ओ0पी0 ब्रहम्पुर',
      'Dhansoi/धनसोइ',
      'Dumraon/डुमरॉव',
      'Industrial Area/औद्योगिक क्षेत्र',
      'Itarhi/इटाढ़ी',
      'Koransarai/कोरानसराय',
      'Krishnabrahm/कृष्णाब्रहम',
      'Model Thana/मॉडल थाना',
      'Muffasil/मुफस्सिल',
      'Murar/मुरार',
      'Nainijor/नैनीजोर',
      'Nawanagar/नावानगर',
      'Naya Bhojpur OP/नया भोजपुर ओ0पी0',
      'Rajpur/राजपुर',
      'Ram Das Rai ke Dera OP/रामदास राय के डेरा ओ0पी0',
      'Sikraul/सिकरौल',
      'Simri/सिमरी',
      'Sonversha OP/सोनवर्षा ओ0पी0',
      'Tilak Rai Ke Hata OP/तिलक राय के हाता ओ0पी0'
    ],
    [
      'ALINAGAR/अलीनगर',
      'ASHOK PAPER MILL/अशोक पेपर मिल ',
      'BAHADURPUR THANA/बहादुरपुर',
      'BAHERA/बहेड़ा',
      'BAHERI/बहेडी',
      'BARGAON/बड़गॉव',
      'BENTA/बेंता',
      'BHALPATTI/भालपट्टी',
      'BIROUL/बिरौल',
      'FEKLA/फेकला',
      'GHANSHYAMPUR/घनश्यामपुर',
      'HAYAGHAT/हायाघाट',
      'JALE/जाले',
      'JAMALPUR/जमालपुर',
      'KAMTOL THANA/कमतौल',
      'K ASTHAN/कुशेश्वरस्थान',
      'KEOTI/केवटी ',
      'KOTWALI/कोतवाली',
      'LAHERIASARAI/लहेरिया सराय',
      'LNMU/ल०ना०वि०वि०',
      'MABBI/मब्बी',
      'MANIGACHHI/मनगाछी',
      'MORO/मोरो',
      'NAGAR/नगर ',
      'NEHRA/नेहरा',
      'PATOR/पतौर',
      'RAIYAAM THANA/रैयाम',
      'SADAR/सदर',
      'SAKATPUR/सकतपुर',
      'SIMRI /सिमरी बाजार',
      'SINGHWARA/सिंघवाड़ा',
      'SONKI/सोनकी',
      'TILKESHWAR/तिलकेश्‍वर',
      'VISHANPUR THANA/विशनपुर थाना',
      'WAJITPUR/बाजितपुर'
    ],
    [
      'Aamas/आमस',
      'Aanti/ऑती',
      'Alipur/अलीपुर',
      'Atri/अतरी',
      'Bahera/बहेरा',
      'Bankey Bazar/बॉके बाजार',
      'Barachatti/बाराचट्टी',
      'Belaganj/बेलागंज',
      'Bhadvar/भदवर',
      'Bodhgaya/बोधगया',
      'Bodhi Bigha/बोधि विगहा',
      'Buniyadganj/बुनियादगंज',
      'Chakand Thana/चाकन्द थाना',
      'Chandauti/चन्दौती',
      'Cherki Thana/चेरकी थाना',
      'Chhakarbandha/छकरबंधा',
      'Civil lines/सिविल लाईन',
      'Delha/डेल्हा',
      'Dhangai/धनगाई',
      'Dobhi/डोभी',
      'Dumariya/डुमरिया',
      'Fatehpur/फतेहपुर',
      'Gahlor/गहलौर',
      'Guraru/गुरारू',
      'Gurpa/गुरपा',
      'Gurua/गुरुआ',
      'Imamganj/इमामगंज ',
      'Khizersarai/खिजरसराय',
      'konch/कोंच',
      'Kothi/कोठी',
      'Kotwali/कोतवाली',
      'Lutua/लुटुआ',
      'Magadh Medical/मगध मेडिकल',
      'Magadh University/मगध विश्वविद्यालय',
      'Mahkar/महकार',
      'Maigra/मैगरा',
      'Main/मेन',
      'Mau Thana/मउ थाना',
      'Mohanpur/मोहनपुर',
      'Muffasil/मुफसिल',
      'Nimchak Bathani/नीमचक बथानी',
      'Pai Bigha OP/पाई बिगहा ओ0पी0',
      'Panchanpur thana/पंचानपुर थाना',
      'Paraiya/परैया',
      'Pura/पुरा',
      'Rampur/रामपुर',
      'Raushanganj/रौशनगंज',
      'Sarbahda Thana/सरबहदा थाना',
      'Sherghati/शेरघाटी',
      'Sindhugarh/सिन्धुगंढ़',
      'Sohail/सोहैल',
      'Tankuppa Thana/टनकुप्पा थाना',
      'Tikari/टिकारी',
      'vishnupad/विष्णुपद',
      'Wazirganj/वजीरगंज'
    ],
    [
      'Baikunthpur/बैकुण्ठपुर',
      'Barauli/बरौली',
      'Bhore/भोरे',
      'Bijaipur/बिजयीपुर',
      'Bishwambharpur/विश्वम्भरपुर',
      'Gopalpur/गोपालपुर',
      'Hathua/हथुआ',
      'Kateya/कटेया',
      'Kuchaikote/कुचायकोट',
      'Madhopur/माधोपुर',
      'Mahmmadpur/महम्मदपुर',
      'Manjhagarh/मांझागढ़',
      'Mirganj/मीरगंज',
      'Phulwaria/फुलवरिया',
      'Shripur/श्रीपुर',
      'Sidhwalia/सिधवलिया',
      'Thawe/थावे',
      'Town Thana-Gopalganj/नगर थाना - गोपालगंज',
      'Uchkagaon/उचकागाँव',
      'Yadopur/यादवपुर'
    ],
    [
      'Barhat/बरहट',
      'Chakai/चकाई',
      'Chandradeep/चन्द्रदीप',
      'Chandramandih/चन्द्रमंडी',
      'CharkaPatthar/चरकापत्थर',
      'Garahi/गरही',
      'Gidhaur/गिद्धौर',
      'Jamui/जमुई',
      'Jhajha/झाझा',
      'Khaira/खैरा',
      'Lachhuar/लछुआड़',
      'Laxmipur/लक्ष्मीपुर',
      'Malaypur/मलयपुर',
      'Sikandra/सिकन्दरा',
      'Simultala/सिमुलतला',
      'Sono/सोनो'
    ],
    [
      'BARABAR PARYATAN THANA/बराबर पर्यटन थाना',
      'BHELAWAR/भेलावर ओ0पी0',
      'GHOSHI/घोषी',
      'HULASGANJ/हुलासगंज',
      'JEHANABAD NAGAR THANA/जहानाबाद नगर थाना',
      'KADAUNA/कड़ौना ओ0पी0',
      'KAKO/काको',
      'KALPA/कल्पा ओ0पी0',
      'MAKHADUMPUR/मखदुमपुर',
      'OKARI/ओकरी ओ0पी0',
      'PALI/पाली',
      'PARASBIGHA/परसविगहा',
      'SHAKURABAD/शकुराबाद',
      'TEHTA/टेहटा ओ0पी0',
      'UMTA DHARNAI/उमता धरनई ओ0पी0',
      'VISHUNGANJ/विशुनगंज ओ0पी0'
    ],
    [
      'Adhaura/अधौरा',
      'Belaow/बेलॉव',
      'Bhabua/भभुआ',
      'Bhagwanpur /भगवानपुर',
      'Chainpur/चैनपुर',
      'Chand/चॉद',
      'Durgawati/दुर्गावती',
      'Karamchat/करमचट',
      'Kuchila/कुछिला',
      'Kudhani/कुढ़नी',
      'Kudra /कुदरा',
      'Lohara/लोहरा',
      'Mohania/मोहनियां',
      'Nuaon/नुऑव',
      'Ramgarh/रामगढ़',
      'Sonhan /सोनहन'
    ],
    [
      'Abadpur/आबादपुर',
      'Amdabad/अमदाबाद',
      'Azamnagar/आजमनगर',
      'Baliya Beloon/बलिया बेलौन',
      'Balrampur/बलरामपुर',
      'Barari/बरारी',
      'Barsoi/बारसोई',
      'Dandkhora/डण्डखोरा',
      'Falka/फलका',
      'Hasanganj/हसनगंज',
      'Kachana OP/कचना ओo पीo',
      'Kadwa/कदवा',
      'Katihar Muffassil/कटिहार मुफ्फसील',
      'Katihar Nagar/कटिहार नगर',
      'Katihar Sahayak/कटिहार सहायक',
      'Kolasi OP/कोलासी ओo पीo',
      'Korha/कोढ़ा',
      'Kursela/कुर्सेला',
      'Manihari/मनिहारी',
      'Mansahi/मनसाही',
      'Pothia OP/पोठिया ओo पीo',
      'Pranpur/प्राणपुर',
      'Raushana OP/रोशना ओo पीo',
      'Rautara/रौतारा',
      'Salmari OP/सालमारी ओo पीo',
      'Semapur OP/सेमापुर ओo पीo',
      'Sudhani OP/सुधानी ओo पीo',
      'Telta OP/तेलता ओo पीo'
    ],
    [
      'Alauli/अलौली',
      'Beldaur/बेलदौर',
      'Bharatkhand OP/भरतखंड ओ0पी0',
      'Chautham/चौथम',
      'Chitragupt Nagar/चित्रगुप्त नगर',
      'Gangour/गंगोर',
      'Gogari/गोगरी',
      'Khagaria/खगड़िया',
      'Maheshkhuth/महेशखूँट',
      'Mansi/मानसी',
      'Maraiya/मड़ैया',
      'Morkahi/मोरकाही',
      'Muffasil/मुफसिल',
      'Parbatta/परबत्ता',
      'Pasraha/पसराहा',
      'Paura/पौड़ा'
    ],
    [
      'Arrabari/अर्राबाड़ी',
      'Bahadurganj/बहादुरगंज',
      'Bibiganj/बीवीगंज',
      'Bishanpur/बिशनपुर',
      'Dighalkbank/दिघलबैंक',
      'fatehpur/फतेहपुर',
      'Galgalia/गलगलीया',
      'Garbhandanga/गर्भंडांगा',
      'jiyapokhar/जियापोखड़',
      'Kishanganj/किशनगंज ',
      'Kochadhaman Thana/कोचाधामन',
      'kodhobari/कोढ़ोबाड़ी',
      'Kurlikort/कुर्लीकोट',
      'Paharkatta/पहाड़कट्टा',
      'Pathamari/पाठामारी',
      'Pothia/पोठिया',
      'pouakhali/पौआखाली',
      'Sukhani/सुखानी',
      'Tedhagach/टेढ़ागाछ',
      'Thakurganj /ठाकुरगंज'
    ],
    [
      'Amhara/अमहरा',
      'Bannu bagicha/बन्नूबगीचा',
      'Barhiya/बड़हिया',
      'Chanan/चानन',
      'Halsi/हलसी',
      'Kajra/कजरा',
      'Kawaiya/कवैया',
      'Kiul/किऊल',
      'Lakhisarai/लखीसराय',
      'Manikpur/माणिकपुर',
      'Medni Chowki/मेदनीचौकी',
      'Piparia/पिपरिया',
      'Piri Bazar/पीरीबाजार',
      'Ramgarh Chowk/रामगढ़चौक',
      'Surajgarha/सूर्यगढ़ा',
      'Tetarhat/तेतरहाट',
      'Virupur/वीरूपुर'
    ],
    [
      'Alamnagar/आलमनगर',
      'Arar OP/अरार',
      'Belari OP/बेलाड़ी',
      'Bharrahi OP/भर्राही',
      'Bhatni OP/भतनी',
      'Bihariganj/बिहारीगंज',
      'Chausa/चौसा',
      'Gamhariya /गमहड़िया',
      'Ghailarh/घैलाढ़ ',
      'Gwalpara/गवालपारा',
      'Kumarkhand/कुमारखंड',
      'Madhepura/मधेपुरा',
      'Murliganj/मुरलीगंज',
      'Parmanandpur OP/परमानंदपुर',
      'PhulautOP/फुलौत',
      'Puraini/पुरैनी',
      'Ratwara/रतवाड़ा',
      'Shankarpur/शंकरपुर',
      'Singheshwar/सिद्धेश्वर स्थान',
      'Srinagar hatt/श्रीनगर हाट',
      'Udakishunganj/उदाकिशनगंज'
    ],
    [
      'Andhramath/अंधरामठ थाना',
      'Andhrathadhi/अंधराठाढी थाना',
      'Araria Sangram Thana/अररिया संग्राम थाना',
      'Arer/अरेर थाना',
      'Aunsi Thana/आँसी थाना',
      'Babubarhi/बाबुबरही थाना',
      'Basopatti/बासोपट्टी थाना',
      'Benipatti/बेनीपट्टी थाना',
      'Bhairavsthan/भैरवस्थान थाना',
      'Bheja/भेजा थाना',
      'Bisfi/बिस्फी थाना',
      'Deodha/देवधा थाना',
      'Ghoghardiha/घोघरडीहा थाना',
      'Harlakhi/हरलाखी थाना',
      'Jaynagar/जयनगर थाना',
      'Jhanjharpur/झंझारपुर थाना',
      'Kaluahi/कलुआही थाना',
      'Khajauli/खजौली थाना',
      'Khirhar/खिरहर थाना',
      'Khutauna/खुटौना थाना',
      'Ladaniya/लदनिया थाना',
      'Lakhnaur/लखनौर थाना',
      'Lalmaniya thana/ललमनिया थाना',
      'Laukaha/लौकहा थाना',
      'Laukahi/लौकही थाना',
      'Madhepur/मधेपुर थाना',
      'Madhwapur/मधवापुर थाना',
      'Narhiya Thana/नरहिया थाना',
      'Pandaul/पण्डौल थाना',
      'Patauna thana/पतौना थाना',
      'Phulparas/फुलपरास थाना',
      'Rahika/रहिका थाना',
      'Rajnagar/राजनगर थाना',
      'RS thana/आर0एस0 थाना',
      'Rudrapur/रुद्रपुर थाना',
      'Saharghat/सहारघाट थाना',
      'Sakri/सकरी थाना',
      'Town/नगर थाना'
    ],
    [
      'Asarganj/असरगंज',
      'Bariyarpur/बरियारपुर',
      'Basudevpur/बासुदेवपुर',
      'dharhara/धरहरा',
      'Eastcolony/इस्ट कॉलनी',
      'Gangtaa/गंगटा',
      'Hareenmar/हरिनमार',
      'Harpur/हरपुर',
      'Haveli Kharagpur/हवेली खड़गपुर',
      'Hemjapur/हेमजापुर',
      'Jamalpur/जमालपुर',
      'Kasimbazar/कासीम बाजार',
      'Kotwali/कोतवाली',
      'Laraiyatand/लड़ैयाटाड',
      'Munger Muffasil/मुंगेर मु०',
      'Nayaramnagar/नया रामनगर',
      'Purabsarai/पुरबसराय',
      'Safiyasarai/सफियासराय',
      'Sangrampur/संग्रामपुर',
      'Shampur/शामपुर',
      'Tarapur/तारापुर',
      'Tetiya Bamber/टेटियाबम्बर'
    ],
    [
      'AHIYAPUR PS/अहियापुर थाना',
      'AURAI PS/औराइ थाना',
      'BARIYARPUR OP/बरियारपुर ओ0पी0',
      'BARURAJ PS/बरूराज थाना',
      'BELA PS/बेला थाना',
      'BENIBAD OP/बेनीबाद ओ0पी0',
      'BOCHAHAN PS/बोचहां थाना',
      'BRAHMPURA PS/ब्रह्मपुरा थाना',
      'DEORIA PS/देवरिया थाना',
      'FAKULI OP/फकुली ओ0पी0',
      'GAYGHAT PS/गायघाट थाना',
      'HATHAURI PS/हथौड़ी थाना',
      'HATTHA OP/हत्था ओ0पी0',
      'JAITPUR OP/जैतपुर ओ0पी0',
      'KANTI PS/कांटी थाना',
      'KARJA PS/करजा थाना',
      'KATHAIYA PS/कथैया थाना',
      'KATRA PS/कटरा थाना',
      'KAZIMOHAMMADPUR PS/काजीमोहम्मदपुर थाना',
      'KUDHANI/कुढ़नी थाना',
      'MANIYARI PS/मनियारी थाना',
      'MINAPUR PS/मीनापुर थाना',
      'MITHANPURA PS/मिठनपुरा थाना',
      'MOTIPUR PS/मोतीपुर थाना',
      'MUSHAHARI PS/मुशहरी थाना',
      'PANAPUR OP/पानापुर ओ0पी0',
      'PAROO PS/पारू थाना',
      'PIYAR PS/पीयर थाना',
      'SADAR PS/सदर थाना',
      'SAHEBGANJ PS/साहेबगंज थाना',
      'SAKRA PS/सकरा थाना',
      'SARAIYA PS/सरैया थाना',
      'SIWAIPATTI PS/शिवाईपट्टी थाना',
      'TOWN PS/नगर थाना',
      'TURKI OP/तुर्की ओ0पी0',
      'UNIVERSITY PS/विश्वविद्यालय थाना'
    ],
    [
      'Asthawan/अस्थावॉ',
      'Aungaari/औंगारी',
      'Bhaganbigha/भगन बिगहा',
      'Biharsharif/बिहारशरीफ',
      'Bind/बिंद',
      'Chandi/चंडी',
      'Chero/चेरो',
      'Chhabilapur/छबिलापुर',
      'Chiksaura/चिकसौर',
      'Deepnagar/दीपनगर',
      'Ekangarsarai/एकंगर साराय',
      'Ghokhulpur/गोकुलपुर',
      'Giriyak/गिरियक',
      'Harnaut/हरनौत',
      'Hilsa/हिलसा मु0',
      'Islampur/इस्लामपुर',
      'Kalyan Bigha OP/कल्याण बिगहा',
      'karaiparsurai/करायपरसुराय',
      'Katrisara/कतरीसराय',
      'Khudaganj/खुदागंज',
      'Laheri/लहेरी',
      'Manpur/मानपुर',
      'nagarnausa/नगरनौसा',
      'Nalanda/नालंदा',
      'Nature Safari/नेचर सफारी',
      'Noorsarai/नूरसराय',
      'Parwalpur/परवलपुर',
      'Pawapuri OP/पावापुरी',
      'Peerbigha OP/पीरबिगहा',
      'Rahui/रहुई',
      'Rajgir/राजगीर',
      'Sare/सारे',
      'Sarmera/सरमेंरा',
      'Shohsarai/सोहसराय',
      'Silao/सिलाव',
      'Telhara/तेलहाड़ा',
      'Telmar/तेलमर',
      'Tharthari/थरथरी',
      'wen/वेन',
      'Wena/वेना थाना'
    ],
    [
      'AKBARPUR/अकबरपुर',
      'BUNDELKHAND/बुन्देलखंड',
      'DHAMAUL/धमौल',
      'GOVINDPUR/गोविन्दपुर',
      'HISUA/हिसुआ',
      'KADIRGANJ/कादिरगंज',
      'KASHICHAK/काशीचक',
      'KAWAKOL/कौआकोल',
      'MESKAUR/मशकौर',
      'NARDIGANJ/नारदीगंज',
      'NARHAT/नरहट',
      'Nawada/नवादा',
      'NAWADA MUFFASIL/नवादा मु0',
      'NAWADA SADAR/नवादा सदर',
      'NEMDAAR GANJ/नेमदारगंज',
      'PAKRIWARAMA/पकरीबरावॉ',
      'PARNA DABAR/परनाडाबर',
      'RAJAULI/रजौली',
      'ROH/रोह',
      'RUPOW/रूपों',
      'SAHPUR/शाहपुर',
      'SIRDALA/सिरदल्ला',
      'SITAMARHI/सीतामढ़ी',
      'THAALI/थाली',
      'WARSALIGANJ/वारसलीगंज'
    ],
    [
      'Bagaha/बगहा',
      'Bairia Police Station/बैरिया थाना',
      'Balthar Police Station/बलथर थाना',
      'Banuchhapar thana/बानुछापर थाना',
      'Bathwariya/बथवरिया',
      'Bhairoganj/भैरोगंज',
      'Bhangaha Police Station/भंगहा थाना',
      'Bhitaha/भितहॉ',
      'Chanpatia Police Station/चनपटिया थाना',
      'Chautarwa/चौतरवा',
      'Chiutaha OP/चिऊटाहॉ ओ0पी0',
      'Dhanha/धनहा',
      'Gabarahiya/गोबरहिया',
      'Gaunaha Police Station/गौनाहा थाना',
      'Gobardhana/गोबर्धना',
      'Gopalpur Police Station/गोपालपुर थाना',
      'Inarwa Police Station/इनरवा थाना',
      'Jagdispur Police Station/जगदीशपुर थाना',
      'Kalibagh Police Station/कालीबाग थाना',
      'Kangli Police Station/कंगली थाना',
      'Kumarbagh Police Station/कुमारबाग थाना',
      'Laukariya/लौकरिया',
      'Lauria Police Station/लौरिया थाना',
      'Mainatand Police Station/मैनाटॉड थाना',
      'Majhaulia Police Station/मझौलिया थाना',
      'Manpur Police Station/मानपुर थाना',
      'Manuapul Police Station/मनुआपुल थाना',
      'Matiyariya Police Station/मटिअरिया थाना',
      'Muffasil Police Station/मुफ्फसिल थाना',
      'Nadi/नदी',
      'Nagar Police Station/नगर थाना',
      'Nautan Police Station/नौतन थाना',
      'Nawalpur Police Station/नवलपुर थाना',
      'Nawrangiya/नौरंगिया',
      'Patkhauli OP/पटखौली ओ0पी0',
      'Piprasi/पीपरासी',
      'Purushottampur Police Station/पुरुषोतमपुर थाना',
      'Ramnagar/रामनगर',
      'Sahodra Police Station/सहोदरा थाना',
      'Sanichari Police Station/शनिचरी थाना',
      'Sathi Police Station/साठी थाना',
      'Semra/सेमरा',
      'Shikarpur Police Station/शिकारपुर थाना',
      'Shrinagar Police Station/श्रीनगर थाना',
      'Sikta Police Station/सिकटा थाना',
      'Sirisiya Police Station/सिरिसिया थाना',
      'Thakraha/ठकराहां',
      'Valmikinagar/वाल्मीकिनगर',
      'Yogapatti Police Station/योगापट्टी थाना'
    ],
    [
      'AGAM KUWAN/अगमकुंऑ',
      'AIR PORT THANA/हवाई अडडा',
      'ALAM GANJ THANA/आलमगंज',
      'ATHMALGOLA THANA/अथमलगोला',
      'BAHADUR PUR THANA /बहादुरपुर',
      'BAI PASS THANA/बाईपास',
      'BAKHTIYARPUR THANA/बखतियारपुर',
      'BARH/बाढ़',
      'BELCHHI THANA/बेलछी',
      'BEUR THANA/बेउर',
      'BHADAUR THANA/भदौर',
      'BHAGWANGANJ/भगवानगंज',
      'BIHTA THANA/बिहटा',
      'BIKRAM THANA/बिक्रम',
      'BUDHA COLONY/बुद्धा कॉलोनी',
      'Chitragupta Nagar/चित्रगुप्त नगर',
      'CHOK THANA/चौक थाना',
      'DANAPUR THANA/दानापुर',
      'DANIYAWAN THANA/दनियावां',
      'DHANARUA THANA/धनरुआ',
      'DIDARGANJ THANA/दीदारगंज',
      'DIGHA/दीघा',
      'DULHIN BAZAR THANA/दुल्हिन बाज़ार',
      ' FATUHA THANA /फतुआ',
      'GANDHI MAIDAN THANA/गांधी मैदान',
      'GARDANIBAGH THANA/गर्दनीबाग',
      'GAURI CHAK THANA/गौरीचक',
      'GHOSWARI/घोसवरी',
      'GOPAL PUR THANA/गोपालपुर',
      'HATHIDAH THANA/हाथीदह',
      'IIT BIHTA AMAHARA/आईआईटी बिहटा अमहरा',
      'JAKKAN PUR THANA/जक्कनपुर',
      'JANI PUR THANA/जानीपुर',
      'KADAM KUWAN THANA/कदमकुंआ थाना',
      'KADIRGANJ THANA/कादिरगंज',
      'KANKER BAGH THANA/कंकड़बाग',
      'KHAGAUL TAHAN/खगौल थाना',
      'KHAJEKALA THANA/खॉजेकला',
      'KHUSRUPUR THANA/खुशरूपुर',
      'KIHIRIMORE THANA/खानपुर खीड़ीमोड़',
      'KOTWALI THANA/कोतवाली',
      'MAL SALAMI THANA/मालसलामी',
      'MANER THANA/मनेर',
      'MARANCHI THANA/मरॉची',
      'MASAURHI THANA/मसौढ़ी',
      'MEHADI GANJ THANA/मेंहदीगंज',
      'MOKAMA THANA/मोकामा',
      'NADI THANA/नदी थाना',
      'NAUBATPUR THANA/नौबतपुर',
      'NEURA THANA/नेउरा',
      'NTPC/एन0टी0पी0सी0 बाढ़',
      'PALI GANJ THANA/पालीगंज',
      'PANCH MAHALA THANA/पंचमहला',
      'PANDARAK THANA/पंडारक',
      'PARSA BAZAR THANA/परसा बाजार',
      'PATLIPUTRA/पाटलीपुत्रा',
      'PATRAKAR NAGAR THANA/पत्रकार नगर',
      'PHULWARI THANA /फुलवारीशरीफ',
      'Piplawan - Pitwans/पिपलावॉ - पीतवांस',
      'PIPRA THANA/पीपड़ा',
      'PIR BAHORE THANA/पीरबहोर',
      'PUNPUN THANA/पुनपुन',
      'RAJIV NAGAR/राजीवनगर',
      'RAM KRISHNA NAGAR THANA/रामकृष्णा नगर',
      'RANI TALAB THANA/रानीतालाब',
      'RUPAS PUR THANA/रूपसपुर',
      'SACCHIWALAY THANA/सचिवालय',
      ' SAKSOHARA THANA/सकसोहरा',
      'SALIMPUR/सालीमपुर',
      'SHAHJAHANPUR THANA/शाहजहांपुर',
      'SHAPUR THNANA/शाहपुर थाना',
      'SHASTRINAGAR THANA/शास्त्रीनगर',
      'SIGODI THANA /सिंगौरी',
      'S K PURI THANA/श्रीकृष्णपुरी',
      'SULTAN GANJ THANA/सुल्तानगंज थाना'
    ],
    [
      'Adapur/आदोपुर',
      'Areraj OP/अरेराज ओपी',
      'Banjariya/बंजरिया',
      'Bhelahi/भेलाही',
      'Bhopatpur OP/भोपतपुर',
      'Chakiya PS/चकिया पी एस',
      'Chhatauni/छतौनी',
      'Chhauradano/छोड़ादानो',
      'Chiraiya/चिड़ैया',
      'Darpa/दरपा',
      'Dhaka PS/ढाका पी एस',
      'Dumariya Ghat/डुमरियाघाट (खजुरिया)',
      'Fenhara/फेनहारा',
      'Ghorasahan/घोड़ासहन',
      'Govindganj/गोविंदगंज',
      'Haraiya OP/हरैया',
      'Harapur/हरपुर',
      'Harsidhi/हरसिद्धी',
      'Jharoukhar/झरौखर',
      'Jitna/जितना',
      'Kalyanpur/कल्याणपुर',
      'Kesariya PS/केसरिया पी एस',
      'Kotwa/कोटवा',
      'Kundwa Chainpur/कुंडवा चैनपुर',
      'Lakhaura/लखौरा',
      'Madhuban PS/मधुबन पी एस',
      'Mahuawa/महुआवॉ',
      'Malahi/मलाही',
      'Mehsi/महेशी',
      'Muphashil PS/मुफस्सिल पी एस',
      'Nakardei/नकरदेई',
      'Pachpakari OP/पचपकड़ी',
      'Paharpur/पहाड़पुर',
      'Pakridayal/पकड़ी दयाल',
      'Palnawa/पलनावॉ',
      'Patahi/पताही',
      'Pipra/पीपरा',
      'Piprakothi/पीपरा कोठी',
      'Rajepur/राजेपुर',
      'Ramgarhwa/रामगढ़वा',
      'Raxaul T OP/रक्सौल टी0ओ0पी0',
      'Sangrampur/संग्रामपुर',
      'Shikarganj/शिकारगंज',
      'Sugauli/सुगौली',
      'Town Police Station/टाउन पुलिस स्टेशन',
      'Turkauliya/तुरकौलियाँ'
    ],
    [
      'Akbarpur OP/अकबरपुर ओ0पी0',
      'Amour/अमौर',
      'Angarh/अनगढ़',
      'Baisi/बायसी',
      'Baliya OP/बलिया ओ0पी0',
      'Banmankhi/बनमनखी',
      'Bhawanipur/भवानीपुर',
      'B Kothi/बी0 काठी0',
      'Champa Nagar/चम्पानगर',
      'Dagarua/डगरुआ',
      'Dhamdaha/धमदाहा',
      'Jalalgarh/जलालगढ़',
      'Janki Nagar/जानकीनगर',
      'Kasba/कसबा',
      'K Hat/के0 हाट',
      'K Nagar/के0 नगर',
      'Madhubani TOP/मधुबनी टी0ओ0पी0',
      'Mirganj/मीरगंज',
      'Mohanpur OP/मोहनपुर ओ0पी0',
      'Mufassil/मुफस्सिल',
      'Raghuvansh Nagar OP/रघुवंश नगर ओ0पी0',
      'Rauta/रौटा',
      'Rupauli/रूपौली',
      'Sadar/सदर',
      'Sahayak Khazanchi/सहायक खजांची',
      'Sahayak Maranga/सहायक मरंगा',
      'Sarsi/सरसी',
      'Srinagar/श्री नगर',
      'Tikapatti/टीकापट्टी'
    ],
    [
      'AGRER/अगरेर',
      'AKORHIGOLA/अकौडीगोला',
      'AMJHOR/अमझौर',
      'BADDEE/बड्डी',
      'BAGHAILA/बघेला',
      'BAIJLA/बैजला',
      'BARHARI/बड़हरी',
      'BHANAS/भानस',
      'BIKRAMGANJ/बिक्रमगंज',
      'CHENARI/चेनारी ',
      'CHUTIYA/चुटिया',
      'DALMIYANAGAR/डालमियानगर',
      'DARIGAON/दरीगांव',
      'DARIHAT/दरिहट',
      'DAWATH/दावत ',
      'DEHRI MUFASSIL/डेहरी मु०',
      'DEHRI NAGAR/डेहरी नगर',
      'DHARMPURA/धर्मपुरा',
      'DINARA/दिनारा',
      'INDRAPURI/इंन्द्रपुरी',
      'KACHHAWAN/कछबॉ',
      'KARAKAT/काराकाट',
      'KARGAHAR/करगहर',
      'KOCHAS/कोचस',
      'NASARIGANJ/नासरीगंज',
      'NATWAR/नटवार',
      'NAUHATTA/नवहटा',
      'NOKHA/नोखा',
      'PARASTHUAN/परसथुआँ',
      'RAJPUR/राजपुर',
      'ROHTAS/रोहतास ',
      'SANJHAULI/संझौली',
      'SASARAM/सासाराम',
      'SASARAM MUFASSIL/सासाराम मु०',
      'SHEOSAGAR/शिवसागर',
      'SIDHEE/सीढ़ी',
      'SURYA PURA/सूर्यपुरा ',
      'TILAUTHU/तिलौथु',
      'YADHUNATHPUR/यधुनाथपुर'
    ],
    [
      'BAIJNATHPUR POLICE SHIVIR/बैजनाथपुर पुलिस शिविर',
      'BALWAHAT OP/बलवाहाट ओ0पी0',
      'BANGAON/बनगॉव',
      'BANMA ITAHARI/बनमा ईटहरी ओ0पी0',
      'BASNAHI/बसनही ',
      'BIHRA/बिहरा ',
      'CHIRAIYA OP/चिड़ैया ओ0पी0',
      'DARHAR OP/डरहार ओ0पी0',
      'JALAI OP/जलई ओ0पी0',
      'KANARIA OP/कनरिया ओ0पी0',
      'KASHNAGAR OP/काशनगर ओ0पी0',
      'MAHISHI/महिषी',
      'NAUHATTA/नवहट्टा',
      'PASTPAR POLICE SHIVIR/पस्तपार पुलिस शिविर',
      'PATARGHAT OP/पतरघट ओ0पी0',
      'SAHARSA SADAR/सहरसा सदर',
      'SALKHUWA/सलखुआ',
      'SIMRI BAKHTIYARPUR/सिमरी बख्तियारपुर',
      'SONBARSA KACHARI/सोनवर्षा कचहरी',
      'SONBARSA RAJ/सोनवर्षा राज',
      'SOUR BAZAR/सौरबाजार'
    ],
    [
      'Angarghat/अंगारघाट',
      'Bangra/बंगरा',
      'Bibhutipur/बिभूतिपुर',
      'Bithan/बिथान',
      'Chakmehsi/चकमेहसी',
      'Dalsingsarai/दलसिंहसराय',
      'Ghataho/घटहो',
      'Halai/हलई',
      'Hasanpur/हसनपुर',
      'Hathauri/हथौड़ी',
      'Kalyanpur/कल्याणपुर',
      'Karpoorigram/कर्पूरीग्राम',
      'Khanpur/खानपुर',
      'Larjhaghat/लरझाघाट',
      'Mathurapur/मथुरापुर',
      'Mohanpur/मोहनपुर',
      'Mohiuddin Nagar/मोहिउद्दीनगर',
      'Mufassil/मुफ्फसिल',
      'Musrigharari/मुसरीघरारी',
      'Pusa/पूसा',
      'Rosera/रोसड़ा',
      'Sarairanjan/सरायरंजन',
      'Shahpur Patori/शाहपुर पटोरी',
      'Shivaji Nagar/शिवाजीनगर',
      'Singhia/सिंघिआ',
      'Tajpur/ताजपुर',
      'Town/नगर',
      'Ujiarpur/उजियारपुर',
      'Vidyapati Nagar/विद्यापतीनगर',
      'Waini/बैनी',
      'Waris Nagar/वारिसनगर'
    ],
    [
      'Akilpur/अकिलपुर',
      'Amnour/अमनौर',
      'Awatarnagar/अवतारनगर',
      'Baniayapur/बनियापुर',
      'Bhagwan Bazar/भगवान बाज़ार ',
      'Bheldi/भेल्दी',
      'Dariyapur/दरियापुर',
      'Daudpur/दाउदपुर ',
      'Derni/डेरनी',
      'Dighwara/दिघवारा ',
      'Doriganj/डोरीगंज',
      'Ekma/एकमा',
      'Garkha/गरखा',
      'Gaura Bazar OP/गौरा बाजार ओ0पी0',
      'Hariharnath OP/हरिहरनाथ ओ0पी0',
      'Ishuapur/इशुआपुर',
      'Jalalpur/जलालपुर',
      'Janta Bazar/जनता बाजार',
      'Khairah/खैरा',
      'Kopa/कोपा',
      'Maker/मकेर',
      'Manjhi /माँझी',
      'Marhowrah/मढ़ौरा',
      'Mashrakh/मशरक',
      'Mufassil/मुफस्सिल',
      'Nagra OP/नगरा ओ0पी0',
      'Nayagoan/नयागॉव',
      'Pahleja OP/पहलेजा ओ0पी0',
      'Panapur/पानापुर',
      'Parsa/परसा',
      'Rasulpur/रसुलपुर',
      'Revelganj/रिविलगंज',
      'Sahajitpur/सहाजितपुर',
      'Sonepur/सोनपुर',
      'Taraiya/तरैया',
      'Town/नगर'
    ],
    [
      'Ariari/अरियारी',
      'Barbigha/बरबिघा',
      'Baughat/बाउघाट',
      'Chewara/चेबडा',
      'Hatianwan/हथियावॉ',
      'Jairampur/जयरामपुर',
      'Karande/करन्डे',
      'Kasar/कसार',
      'Kewati/केवटी',
      'Korma/कोरमा',
      'Kusumbha/कुसुम्भा',
      'Mahuli/माहुली',
      'Mehus/मेहुष',
      'Mission/मिशन',
      'Sheikhpura/शेखपुरा',
      'Shekhopursarai/शेखोपुरसराय',
      'Sirari/सिरारी'
    ],
    [
      'FATEHPUR PS/फतेहपुर थाना',
      'HIRAMMA PS/हिरम्मा थाना',
      'PIPRAHI PS/पिपराही थाना',
      'PURNAHIYA PS/पुरनहिया थाना',
      'SHEOHAR PS/शिवहर थाना',
      'SHYAMPUR BHATHAN PS/श्यामपुर भटहाँ थाना',
      'TARIYANI CHHAPRA PS/तरियानी छपरा थाना',
      'TARIYANI PS/तरीयानी थाना'
    ],
    [
      'Bairgania/बैरगनिया',
      'Bajpatti/बाजपटी',
      'Bathnaha/बथनाहा',
      'Bela/बेला',
      'Belsand/बेलसंड',
      'Bhittha/भिठ्ठा',
      'Bhutahi/भूतही',
      'Bokhra/बोखड़ा',
      'Choraot/चोरौत',
      'Dumra/डुमरा',
      'Garha/गाढ़ा',
      'Kanhauli/कन्हौली',
      'Mahindwara/महिन्दवारा',
      'Majorganj/मेजरगंज',
      'Mehsaul/मेहसौल',
      'Nanpur/नानपुर',
      'Parihar/परिहार',
      'Parsauni/परसौनी',
      'Punaora/पुनौरा',
      'Pupri/पुपरी',
      'Riga/रीगा',
      'Runnisaidpur/रून्नी सैदपुर',
      'Sahiyara/सहियारा',
      'Sitamarhi/सीतामढ़ी',
      'Sonbarsa/सोनबरसा',
      'Suppi/सुप्पी',
      'Sursand/सुरसंड',
      'Tariyani Chhapra/तरियानी छपरा'
    ],
    [
      'Andar/आन्दर',
      'Asaon/असॉव',
      'Barharia/बड़हरिया',
      'Basantpur/बसंतपुर',
      'Bhagwanpur hatt/भगवानपुर हाट',
      'Chainpur thana/चैनपुर थाना',
      'Darauli/दरौली',
      'Daraunda/दरौंदा',
      'Dhanauti thana/धनौती थाना',
      'G B Nagar/जी0बी0 नगर',
      'Goreyakothi/गोरियाकोठी',
      'Guthani/गुठनी',
      'Hussainganj/हुसैनगंज ',
      'Jamo Bazar/जामो बाजार',
      'Lakri naveeganj thana/लकड़ी नवीगंज थाना',
      'Mahadewa thana/महादेवा थाना',
      'Maharajganj /महराजगंज',
      'Mairwa/मैरवा',
      'M H Nagar thana/एम० एच० नगर थाना',
      'Nautan/नौतन',
      'Pachrukhi/पचरुखी ',
      'Raghunathpur/रघुनाथपुर',
      'Sarai thana/सराय थाना',
      'Siswan/सिसवन',
      'Siwan Muffasil/सिवान मु0',
      'Siwan Nagar/सिवान नगर',
      'Ziradei/जीरादेई'
    ],
    [
      'Balua Bajar/बलुआ बाजार',
      'Bhaptiyahi/भपटियाही',
      'Bhimnagar/भीमनगर',
      'Bhimpur/भीमपुर',
      'Birpur/वीरपुर',
      'Chhatapur/छातापुर',
      'Dagmara/डगमारा',
      'Jadiya/ज़दिया',
      'Karjain/करजाईन',
      'Kishanpur/किशनपुर',
      'Kunauli/कुनौली',
      'Lalitgram/ललितग्राम',
      'Laukaha/लौकहा',
      'Marauna/मरौना',
      'Nirmali/निर्मली',
      'Pipra/पिपरा',
      'Pratapganj/प्रतापगंज',
      'Raghopur/राघोपुर',
      'Rajeshwari/राजेशवरी',
      'Ratanpura/रतनपुरा',
      'Supaul/सुपौल',
      'Supaul Nadi Thana/सुपौल नदी थाना',
      'Triveniganj/त्रिवेणीगंज'
    ],
    [
      'BALIGAON THANA/बलिगॉव',
      'BARANTI OP/बरॉटी',
      'BELSAR OP/बेलसर',
      'BHAGWANPUR THANA/भगवानपुर',
      'BIDUPUR THANA/बिदुपुर',
      'CHANDPURA OP/चांदपुरा',
      'DESARI THANA /देसरी',
      'GANGABRIJ THANA/गंगाब्रिज थाना',
      'GORAUL THANA /गोरौल',
      'HAJIPUR NAGAR/हाजीपुर नगर ',
      'HAJIPUR SADAR /हाजीपुर',
      'INDUSTRIAL AREA/औधोगिक',
      'JANDAHA THANA/जनदाहा',
      'JURAWANPUR THANA/जुड़ावनपुर',
      'KARTAHAN THANA/करताहां थाना',
      'KATHARA OP/कटहरा',
      'LALGANJ THANA/लालगंज',
      'MAHNAR THANA/महनार',
      'MAHUA THANA/महुआ',
      'PATEPUR THANA/पातेपुर',
      'RAGHOPUR THANA /राघोपुर',
      'RAJAPAKAR THANA/राजापाकड़',
      'RUSTAMPUR OP/रुस्तमपुर',
      'SAHDEI OP/सहदेइ',
      'SARAI THANA/सराय',
      'TISIAUTA THANA/तीसीऔटा',
      'VAISHALI THANA/वैशाली'
    ]
  ]
};

const casts = [
  [
    'Kapadia / कपरिया',
    'Kanu / कानू',
    'Kalandar / कलन्दर',
    'Kochh / कोछ',
    'Kurmi (Mahto) (Jharkhand autonomous area) / कुर्मी (महतो) झारखंड स्वशासी क्षेत्र',
    'Kewat (Kaut) / केवट (कउट)',
    'Kadar / कादर',
    'Kaura / कोरा',
    'Korku / कोरकू',
    'Kaibart / केवर्त',
    'Khatwa / खटवा',
    'Khatouri / खतौरी',
    'Khangar / खंगर',
    'Khatik / खटिक',
    'Khelta / खेलटा',
    'Gorhi (Chhabi) / गोड़ी (छावी)',
    'Gangai (Ganesh) / गंगई (गणेश)',
    'Gangota / गंगोता',
    'Gandharb / गंधर्व',
    'Gulgulia / गुलगुलिया',
    'Chain / चांय',
    'Chapota / चपोता',
    'Chandrabansi (Kahar, Kamkar) / चन्द्रवंशी(कहार, कमकर)',
    'Tikulhar / टिकुलहार',
    'Dhekaru / ढेकारू',
    'Tanti (Tatwa)/तांती(ततवा)',
    'Tamaria / तमरिया',
    'Turha / तुरहा',
    'Tiar / तियर',
    'Dhanuk / धानुक',
    'Dhamin / धामिन',
    'Dhimar / धीमर',
    'Dhanwar / धनवार',
    'Nonia / नोनिया',
    'Nai / नाई',
    'Namsudar / नामशुद्र',
    'Pandi / पाण्डी',
    'Pal (Bherihar, Gareri) / पाल (भेड़िहार, गड़ेरी)',
    'Pradhan / प्रधान',
    'Pingania / पिनगनिया',
    'Pahira / पहिरा',
    'Bari / वारी',
    'Beldar / बेलदार',
    'Bind / बिन्द',
    'Shekhra / शेखड़ा',
    'Bagdi / बागदी',
    'Bhuiyar / भुईयार',
    'Bhar / भार',
    'Bhaskar / भास्कर',
    'Mali (Malakar) / माली (मालाकार)',
    'Mangar / मांगर',
    'Madar / मदार',
    'Mallah / मल्लाह',
    'Majhwar / मझवार',
    'Markandey / मारकन्डे',
    'Moriyari / मोरियारी',
    'Malar (Malhor) / मलार (मालहोर)',
    'Molik / मौलिक',
    'Rajdhobi / राजधोबी',
    'Rajbhar / राजभर',
    'Rangwa / रंगवा',
    'Banpar / वनपर',
    'Shota (Shota) / सौटा (सोता)',
    'Sang-Trash (for Nawada district only) / संतराश (केवल नवादा जिले के लिए)',
    'Aghouri / अघोरी',
    'Abdal / अबदल',
    'Kasab (kasai) (Muslim) / कसाब (कसाई) (मुस्लिम)',
    'Chik (Muslim) / चीक (मुस्लिम)',
    'Dafali (Muslim) / डफाली (मुस्लिम)',
    'Dhunia (Muslim) / धुनिया (मुस्लिम)',
    'Dhobi (Muslim) / धोबी (मुस्लिम)',
    'Nut (Muslim) / नट (मुस्लिम)',
    'Pamaria (Muslim) / पमरिया (मुस्लिम)',
    'Bhathiara (Muslim) / भठियारा (मुस्लिम)',
    'Bhat (Muslim) / भाट (मुस्लिम)',
    'Mehtar,Lalbegia,Halalkhor, Bhangi (Muslim) / मेहतर, लालबेगीया, हलालखोर, भंगी(मुस्लिम)',
    'Miriasin (Muslim) / मिरियासीन, (मुस्लिम)',
    'Madari (Muslim) / मदारी (मुस्लिम)',
    'Meershikar (Muslim) / मोरशिकार (मुस्लिम)',
    'Saeen/Fakir/Diwan/Madar (Muslim) / साई/फकीर/दिवान/मदार (मुस्लिम)',
    'Momin (Muslim)(Julaha,Ansari) / मोमिन (मुस्लिम) (जुलाहा,अंसारी)',
    'Amat / अमात',
    'Churihar (Muslim) / चूड़ीहार (मुस्लिम)',
    'Prajapati (Kumhar) / प्रजापति (कुम्हार)',
    'Raeen or Kunjara (Muslim) / राईन या कुंजरा (मुस्लिम)',
    'Soyar / सोयर',
    'Thakurai (Muslim) / ठकुराई (मुस्लिम)',
    'Nagar / नागर',
    'Shershahbadi / शेरशाहबादी',
    'Bakkho (Muslim) / बक्खो (मुस्लिम)',
    'Adrakhi / अदरखी',
    'Chhipi / छीपी',
    'Tili / तिली',
    'Idrisi Or Darji (Muslim) / इदरीसी या दर्जी (मुस्लिम)',
    'Saikalgar (Sikalgar) (Muslim) / सैकलगर (सिकलगर) (मुस्लिम)',
    'Rangrej (Muslim) / रंगरेज (मुस्लिम)',
    'Sinduria Bania,Kaithal Vaishya,Kath Bania / सिंदुरिया बनिया,कैथल वैश्य, कथबनिया',
    'Mukeri (Muslim) / मुकेरी (मुस्लिम)',
    'Itfarosh,Itafarosh,Gadheri,Itpaj Ibrahimi (Muslim) / ईटफरोश, ईटाफरोश,गदहेड़ी,ईटपज इब्राहिमी (मुस्लिम)',
    'Barhi / बढ़ई',
    'Patwa / पटवा',
    'Kamar (Lohar and Karmkar) / कमार (लोहार और कर्मकार)',
    'Dewhar / देवहार',
    'Samari Vaishya / सामरी वैश्य',
    'Haluwai / हलुवाई',
    'Pairgha,Parihar / पैरघा,परिहार',
    'Jaga / जागा',
    'Laheri / लहेड़ी',
    'Rajbanshi (Risia,Deshiya or Polia) / राजवंशी( रिसिया,देशिया या पोलिया)',
    'Kulhaiya / कुल्हैया',
    'Awadh Bania / अवध बनिया',
    'Barai, Tamoli (Chaurasia) / बरई, तमोली (चौरसिया)',
    'Teli / तेली',
    'Dangi / दांगी'
  ],
  [
    'Kagji / कागजी',
    'Kushwaha (Koiri) / कुशवाहा (कोईरी)',
    'Kosta / कोस्ता',
    'Gaddi / गद्दी',
    'Ghatwar / घटवार',
    'Chanau / चनउ',
    'Jadupatia / जदुपतिया',
    'Jogi (jugi) / जोगी (जुगी)',
    'Nalband (Muslim) / नालबंद (मुस्लिम)',
    'Partha / परथा',
    'Bania / बनिया',
    'Yadav / यादव',
    'Rautia / रौतिया',
    'Shivhari / शिवहरी',
    'Sonar / सोनार',
    'Sutradhar / सूत्रधार',
    'Sukiar / सुकियार',
    'Isai Dharmawalambi (Harijan) / ईसाई धर्मावलंबी (हरिजन)',
    'Ishai Dharmawalambi (Anya Pichari Jati) / ईसाई धर्मावलंबी (अन्य पिछड़ी जाति)',
    'Kurmi / कुर्मी',
    'Bhaat,Bhat,Brahmbhat,Rajbhat (Hindu) / भाट,भट,ब्रह्मभट,राजभट (हिन्दू)',
    'Jat (Hindu) / जट (हिन्दू) (सहरसा, सुपौल, मधेपुरा और अररिया जिलों के लिए)',
    'Jat (Muslim) / जट (मुस्लिम) )(मधुबनी, दरभंगा, सीतामढी, खगडिया एवं अररिया जिलों के लिए)',
    'Madaria (Muslim) / मडरिया (मुस्लिम) (मात्र भागलपुर जिला के सन्हौला प्रखंड एवं बांका जिला के धोरैया प्रखण्ड के लिए)',
    'Donwar / दोनवार (केवल मधुबनी और सुपौल जिलों के लिए)',
    'Surjapuri Muslim / सुरजापुरी मुस्लिम (शेख, सैयद, मल्लिक, मोगल, पठान को छोडकर) (केवल पूर्णियां, कटिहार, किशनगंज एवं अररिया जिलों के लिए)',
    'Mallik (Muslim) / मलिक (मुस्लिम)',
    'Sainthwar / सैंथवार',
    'Goswami,Sanyasi,Atith,Athit,Gosai,Jati,Yati / गोस्वामी, सन्यासी,अतिथ,अथीत, गोसाई, जति,यति',
    'Kinnar,Kothi,Hijra,Transgender,Third Gender / किन्नर,कोथी,हिजड़ा,ट्रांसजेंडर (थर्ड जेंडर)'
  ],
  [
    'Bantar / बंतार',
    'Bauri / बौरी',
    'Bhogta / भोगता',
    'Bhuiya / भुईया',
    'Chamar, Mochi, Chamar-Rabidas, Chamar-Ravidas, Chamar-Rohidas, Charmarkar / चमार, मोची, चमार - रबिदास, चमार-रविदास, चमार- रोहिदास, चर्मरकार',
    'Chaupal / चौपाल',
    'Dabgar / दबगर',
    'Dhobi, Rajak / धोबी, रजक',
    'Dom, Dhangad, Bansphor, Dharikar, Dharkar, Domra / डोम, धनगड़, बांसफोड़, धारीकर, धरकर, डोमरा',
    'Dusadh, Dhari, Dharhi / दुसाध, धारी, धारही',
    'Ghasi / घासी',
    'Halalkhor / हलालखोर',
    'Hari,Mehtar, Bhangi / हरि, मेहतर, भंगी',
    'Kanjar / कंजर',
    'Kurariar / कुररियार',
    'Lalbegi / लालबेगी',
    'Musahar / मुसहर',
    'Nat / नट',
    'Pan, Sawasi, Panr / पान, सवासी, पानर',
    'Pasi / पासी',
    'Rajwar / रजवार',
    'Turi / तुरी'
  ],
  [
    'Asur, Agaria / असुर, अगरिया',
    'Baiga / बेगा',
    'Bedia / बेदिया',
    'Binjhia / बिंझिया',
    'Birhor / बिरहोर',
    'Birjia / विरजिया',
    'Chero / चेरो',
    'Chik Baraik / चिक बराइक',
    'Gond / गोंड',
    'Gorait / गोराइत',
    'Ho / हो',
    'Karmali / करमाली',
    'Kharia, Dhelki Kharia, Dudh Kharia, Hill Kharia / खरिया, ढ़ेलकी खड़िया, दूध खड़िया, हिल खड़िया',
    'Kharwar / खरवार',
    'Khond / खोंड',
    'Kisan, Nagesia / किसान, नागेसिया',
    'Kora, Mudi-Kora / कोरा, मुडी- कोरा',
    'Korwa / कोरवा',
    'Lohara, Lohra / लोहारा, लोहरा',
    'Mahli / माहली',
    'Mal Paharia, Kumarbhag Paharia / माल पहरिया, कुमारभाग पहारिया',
    'Munda, Patar / मुण्डा, पातार',
    'Dhangar (Oraon) / धांगड़ (उरांव)',
    'Parhaiya / परहया',
    'Santal / संथाल',
    'Sauria Paharia / सोरिया पहाडिया',
    'Savar / सावर',
    'Kawar / कवार',
    'Kol / कोल',
    'Tharu / थारू',
    'Banjara / बनजारा',
    'Bathudi / बठुडी'
  ],
  [
    'Brahman (Hindu) / ब्राह्मण (हिन्दु)',
    'Rajput (Hindu) / राजपूत (हिन्दु)',
    'Bhoomihar (Hindu) / भूमिहार (हिन्दु)',
    'Kayasth (Hindu) / कायस्थ (हिन्दु)',
    'Saiyad (Muslim) / सैयद (मुस्लिम)',
    'Sheikh (Muslim) / शेख (मुस्लिम)',
    'Pathan (Muslim) / पठान (मुस्लिम)'
  ]
];

const blocks = {
  4: [
    [
      [
        'Araria/अररिया',
        'Jokihat/जोकीहाट',
        'Kursakanta/कुर्साकांटा ',
        'Palasi/पलासी',
        'Raniganj/रानीगंज',
        'Sikty/सीकटी'
      ],
      [
        'BHARGAMA/भरगामा',
        'FORBESGANJ/फोरबिसगंज',
        'NARPATGANJ/नरपतगंज'
      ]
    ],
    [
      [
        'ARWAL/अरवल',
        'KALER/कलेर',
        'KAPRI/करपी',
        'KURTHA/कुर्था',
        'SONBHADRA-BANSI-SURAJPUR/सोनभद्र बंशी सुर्यापूर'
      ]
    ],
    [
      [
        'AURANGABAD/औरंगाबाद',
        'BARUN/बारुण',
        'DEO/देव',
        'KUTUMBA/कुटुम्बा',
        'MADANPUR/मदनपुर',
        'NABINAGAR/नबीनगर',
        'RAFIGANJ/रफीगंज'
      ],
      [
        'DAUDNAGAR/दाउदनगर',
        'GOH/गोह',
        'HASPURA/हसपुरा',
        'OBRA/ओबरा'
      ]
    ],
    [
      [
        'AMARPUR/अमरपुर',
        'BANKA/बाँका',
        'BARAHAT/बाराहाट',
        'BAUSI/बौंसी',
        'BELHAR/बेलहर',
        'CHANDAN/चन्दन',
        'DHURAIYA/धोरैया',
        'FULLIDUMAR/फुल्लीडुमर',
        'KATORIA/कटोरिया',
        'RAJAUN/रजौन',
        'SHAMBHUGANJ/शंभूगंज'
      ]
    ],
    [
      [
        'BAKHRI/बखरी',
        'GADHPURA/गढ़पुरा',
        'NAWKOTHI/नावकोठी'
      ],
      [
        'BALLIA/बलिया',
        'DANDARI/डंडारी',
        'SAHEBPUR KAMAL/साहेबपुरकमाल'
      ],
      [
        'BARAUNI/बरौनी',
        'BEGUSARAI/बेगूसराय',
        'BIRPUR/वीरपुर',
        'MATIHANI/मटिहानी',
        'SAMHO AKHA KURHA/शाम्हो अकहा कुरहा'
      ],
      [
        'CHERIA BARIARPUR/चेरियाबरियारपुर',
        'CHHAURAHI/छौड़ाही',
        'KHODAWANDPUR/खोदावन्दपुर',
        'NAWKOTHI/नावकोठी'
      ],
      [
        'BACHHWARA/बछवाड़ा',
        'BHAGWANPUR/भगवानपुर',
        'MANSURCHAK/मंसूरचक',
        'TEGHRA/तेघड़ा'
      ]
    ],
    [
      [
        'GORADIH/गौराडीह',
        'JAGDISHPUR/जगदीशपुर',
        'NATHNAGAR/नाथनगर',
        'SABOUR/सबौर',
        'SHAHKUND/शाहकुंड',
        'SULTANGANJ/सुल्तानगंज'
      ],
      [
        'Kahalgaon/Colgong',
        'PIRPAINTI/पीरपैंती',
        'SONHAULA/सन्हौला'
      ],
      [
        'BIHPUR/बिहपुर',
        'GOPALPUR/गोपालपुर',
        'ISMAILPUR/ईस्माइलपुर',
        'KHARIK/खरीक',
        'NARAYANPUR/नारायणपुर',
        'NAUGACHHIA/नवगछिया',
        'RANGRACHOWK/रंगरा चौक'
      ]
    ],
    [
      [
        'AGIAON/अगीआँव',
        'ARA/आरा',
        'BARHARA/बड़हरा',
        'GARHANI/गड़हनी',
        'KOILWAR/कोइलवर',
        'SAHAR/सहार',
        'SANDESH/संदेश',
        'UDWANTNAGAR/उदवंतनगर'
      ],
      [
        'BEHEA/बिहिया',
        'JAGDISHPUR/जगदीशपुर',
        'SHAHPUR/शाहपुर'
      ],
      [
        'CHARPOKHARI/चरपोखरी',
        'PIRO/पिरो',
        'TARARI/तरारी'
      ]
    ],
    [
      [
        'BUXAR/बक्सर',
        'CHAUSA/चौसा',
        'ITARHI/इटरही',
        'RAJPUR/राजपुर'
      ],
      [
        'BRAHMPUR/ब्रह्मपुर',
        'CHAKKI/चक्की',
        'CHOUGAIN/चौगाईं',
        'DUMRAON/डुमरांव',
        'KESATH/केसठ',
        'NAWANAGAR/नवानगर',
        'SIMRI/सिमरी'
      ]
    ],
    [
      [
        'ALINAGAR/अलीनगर',
        'BENIPUR/बेनीपुर'
      ],
      [
        'BIRAUL/बिरौल',
        'GAURABAURAM/गौरबौरम',
        'GHANSHYAMPUR/घनश्यामपुर',
        'KIRATPUR/किरतपुर',
        'KUSHESHWAR ASTHAN/कुशेश्वर स्थान',
        'KUSHESWAR ASTHAN EAST/कुशेश्वर स्थान पूर्वी'
      ],
      [
        'BAHADURPUR/बहादुरपुर',
        'BAHERI/बहेरी',
        'DARBHANGA/दरभंगा',
        'HANUMAN NAGAR/हनुमाननगर',
        'HAYAGHAT/हायाघाट',
        'JALE/जाले',
        'KEOTIRUNWAY/केवटी',
        'MANIGACHHI/मनीगाछी',
        'SINGHWARA/सिंघवारा',
        'TARDIH/तारडीह'
      ]
    ],
    [
      [
        'BELAGANJ/बेलागंज',
        'BODHGAYA/बोधगया',
        'FATEHPUR/फ़तेहपुर',
        'GAYA TOWN/गया नगर',
        'MANPUR/मानपुर',
        'TANKUPPA/टंकुप्पा',
        'WAZIRGANJ/वजीरगंज'
      ],
      [
        'ATRI/अतरी',
        'KHIZARSARAI/खिज़रसराय',
        'MOHRA/मोहरा',
        'NEEMCHAK BATHANI/नीमचक बथानी'
      ],
      [
        'AMAS/आमस',
        'BANKEY BAZAR/बाँके बाज़ार',
        'BARACHATTI/बाराचट्टी',
        'DOBHI/दोभी',
        'DUMARIA/डुमरिया',
        'GURUA/गुरुआ',
        'IMAMGANJ/इमामगंज',
        'MOHANPUR/मोहनपुर',
        'SHERGHATTY/शेरघाटी'
      ],
      [
        'GURARU/गुरारू',
        'KONCH/कोंच',
        'PARAIYA/परैया',
        'TEKARI/टेकारी'
      ]
    ],
    [
      [
        'BAIKUNTHPUR/बैकुंठपुर',
        'BARAULI/बरौली',
        'GOPALGANJ/गोपालगंज',
        'KUCHAIKOTE/कुचाई कोटे',
        'MANJHA/माँझा',
        'SIDHWALIYA/सिधवलिया',
        'THAWE/थावे'
      ],
      [
        'BHOREY/भोरेय',
        'BIJAIPUR/विजयपुर',
        'HATHUA/हथुआ',
        'KATAIYA/कटेया',
        'PANCHDEORI/पंचदेवरी',
        'PHULWARIYA/फुलवरिया',
        'UCHKAGAON/उचक्का गाँव'
      ]
    ],
    [
      [
        'BARHAT/बरहट',
        'CHAKAI/चकाई',
        'GIDHOR/गिद्धौर',
        'ISLAMNAGAR ALIGANJ/इस्लाम नगर अलीगंज',
        'JAMUI/जमुई',
        'JHAJHA/झाझा',
        'KHAIRA/खैरा',
        'LAXMIPUR/लक्ष्मीपुर',
        'SIKANDRA/सिकन्दरा',
        'SONO/सोनो'
      ]
    ],
    [
      [
        'GHOSHI/घोषी',
        'HULASGANJ/हुलासगंज',
        'JEHANABAD/जहानाबाद',
        'KAKO/काको',
        'MAKHDUMPUR/मखदुमपुर',
        'MODANGANJ/मोदनगंज',
        'RATNI FARIDPUR/रतनीफरीदपुर'
      ]
    ],
    [
      [
        'ADHAURA/अधौरा',
        'BHABUA/भभूआ',
        'BHAGWANPUR/भगवानपुर',
        'CHAINPUR/चैनपुर',
        'CHAND/चाँद',
        'RAMPUR/रामपुर'
      ],
      [
        'DURGAWATI/दुर्गावती',
        'KUDRA/कुदरा',
        'MOHANIA/मोहनिया',
        'NUAON/ नुऑव  ',
        'RAMGARH/रामगढ़'
      ]
    ],
    [
      [
        'AZAMNAGAR/आज़मनगर',
        'BALRAMPUR/बलरामपुर',
        'BARSOI/बारसोई',
        'KADWA/कदवा'
      ],
      [
        'BARARI/बरारी',
        'DANDKHORA/डंडखोरा',
        'FALKA/फलका',
        'HASANGANJ/हसनगंज',
        'KATIHAR/कटिहार',
        'KORHA/कोढ़ा',
        'KURSELA/कुरसेला',
        'MANSAHI/मनसाही',
        'PRANPUR/प्राणपुर',
        'SAMELI/समेली'
      ],
      [
        'AMDABAD/अमदाबाद',
        'MANIHARI/मनीहारी'
      ]
    ],
    [
      [
        'Beldaur/बेलदौर',
        'GOGRI/गोगरी',
        'PARBATTA/परबत्ता'
      ],
      [
        'ALAULI/अल्लौली',
        'CHAUTHAM/चौथम',
        'KHAGARIA/खगड़िया',
        'MANSI/मानसी'
      ]
    ],
    [
      [
        'BAHADURGANJ/बहादुर गंज',
        'DIGHALBANK/दीघल बैंक',
        'KISHANGANJ/किशनगंज',
        'KOCHADHAMAN/कोचाधमन',
        'POTHIA/पोठिया',
        'TERHAGACHH/तेरागाछ',
        'THAKURGANJ/ठाकुरगंज'
      ]
    ],
    [
      [
        'BARAHIYA/बड़हिया',
        'CHANNAN/चानन',
        'HALSI/हलसी',
        'LAKHISARAI/लखीसराय',
        'PIPARIYA/पिपरिया',
        'RAMGARH CHOWK/रामगढ़ चौक',
        'SURAJGARHA/सूर्यगढ़ा'
      ]
    ],
    [
      [
        'GAMHARIYA/गम्हरिया',
        'GHELARH/घेलाढ',
        'KUMARKHAND/कुमारखंड',
        'MADHEPURA/मधेपुरा',
        'MURLIGANJ/मुरलीगंज',
        'SHANKARPUR/शंकरपुर',
        'SINGHESHWAR/सिंघेश्वर'
      ],
      [
        'ALAMNAGAR/आलमनगर',
        'BIHARIGANJ/बिहारीगंज',
        'CHAUSA/चौसा',
        'GWALPARA/ग्वालपारा',
        'PURANI/पुरैनी',
        'UDAKISHUNGANJ/उदाकिशुनगंज'
      ]
    ],
    [
      [
        'BENIPATTI/बेनीपट्टी',
        'BISFI/बिस्फी',
        'HARLAKHI/हरलाखी',
        'MADHWAPUR/मधवापुर'
      ],
      [
        'BASOPATTI/बासोपट्टी',
        'JAINAGAR/जयनगर',
        'LADANIA/लदनिया'
      ],
      [
        'ANDHRATHARHI/अंधराठाढ़ी',
        'JHANJHARPUR/झंझारपुर',
        'LAKHNAUR/लखनौर',
        'MADHEPUR/मधेपुर'
      ],
      [
        'BABU BARHI/बाबूबरही',
        'KALUAHI/कलुआही',
        'KHAJAULI/खजौली',
        'PANDAUL/पंडौल',
        'RAHIKA/रहिका',
        'RAJNAGAR/राजनगर'
      ],
      [
        'GHOGHARDIHA/घोघरडीहा',
        'LAUKAHA (KHUTAUNA)/खुटौना',
        'LAUKAHI/लौकही',
        'PHULPARAS/फुलपरास'
      ]
    ],
    [
      [
        'KHARAGPUR/हवेली खड़गपुर',
        'TETIABAMBAR/टेटियाबम्बर'
      ],
      [
        'BARIYARPUR/बरियारपुर',
        'DHARHARA/धरहरा',
        'JAMALPUR/जमालपुर',
        'MUNGER SADAR/मुंगेर सदर'
      ],
      [
        'ASARGANJ/असरगंज',
        'SANGRAMPUR/संग्रामपुर',
        'TARAPUR/तारापुर'
      ]
    ],
    [
      [
        'AURAI/औराई',
        'BANDRA/बांद्रा',
        'BOCHAHAN/बोचाहन',
        'GAIGHAT/गयघट',
        'KATRA/कटरा',
        'MINAPUR/मीनापुर',
        'MURAUL/मूरौल',
        'MUSHAHARI/मूशहरी',
        'SAKRA/सकरा'
      ],
      [
        'KANTI/काँटी',
        'KURHANI/कुढ़ानी',
        'MARWAN/मड़वन',
        'MOTIPUR/मोतीपुर',
        'PAROO/पारू',
        'SAHEBGANJ/साहेबगंज',
        'SARAIYA/सरैया'
      ]
    ],
    [
      [
        'ASTHAWAN/अस्थावन',
        'BIHARSHARIF/बिहारशरीफ़',
        'BIND/बिंद',
        'HARNAUT/हरनौत',
        'NOORSARAI/नूरसराय',
        'RAHUI/रहुई',
        'SARMERA/सरमेरा'
      ],
      [
        'CHANDI/चंडी',
        'EKANGARSARAI/एकंगरसराय',
        'HILSA/हिलसा',
        'ISLAMPUR/इस्लामपुर',
        'KARAI PARSURAI/कराय परसुराई',
        'NAGAR NAUSA/नगरनौसा',
        'PARBALPUR/परवलपुर',
        'THARTHARI/थरथरी'
      ],
      [
        'BEN/बेन',
        'GIRIAK/गिरियक',
        'KATRISARAI/कतरीसराय',
        'RAJGIR/राजगीर',
        'SILAO/सिलाव'
      ]
    ],
    [
      [
        'HISUA/हिसुआ',
        'KASHICHAK/काशीचक',
        'KAWAKOLE/कौवाकोल',
        'NARDIGANJ/नारदीगंज',
        'NAWADA/नवादा',
        'PAKRI BARAWAN/PAKRIBARAWAN',
        'WARISALIGANJ/वारिसलीगंज'
      ],
      [
        'AKBARPUR/अकबरपुर',
        'GOBINDPUR/गोविंदपुर',
        'MESCAUR/मेसकौर',
        'NARHAT/नरहट',
        'RAJAULI/रजौली',
        'ROH/रोह',
        'SIRDALA/सिरदला'
      ]
    ],
    [
      [
        'BAGAHA-I/बगहा-1',
        'BAGAHA-II/बगहा-2',
        'BHITAHA/भितहां',
        'MADHUBANI/मधुबनी',
        'PIPRASI/पिपरासी',
        'RAMNAGAR/रामनगर',
        'THAKRAHAN/ठकराहां'
      ],
      [
        'BAIRIA/बैरिया',
        'BETTIAH/बेतिया',
        'CHANPATIA/चनपटिया',
        'JOGAPATTI/योगापट्टी',
        'MAJHAULIA/मझौलिया',
        'NAUTAN/नौतन'
      ],
      [
        'GAUNAHA/गौनाहा',
        'LAURIYA/लौरिया',
        'MAINATAND/मैनाटांड',
        'NARKATIAGANJ/नरकटियागंज',
        'SIKTA/सिकटा'
      ]
    ],
    [
      [
        'ATHAMALGOLA/अथमलगोला',
        'BAKHTIARPUR/बख्तियारपुर',
        'BARH/बाढ',
        'BELCHCHI/बेलछी',
        'GHOSWARI/घोसवरी',
        'MOKAMA/मोकामा',
        'PANDARAK/पंडारक'
      ],
      [
        'BIHTA/बिहटा',
        'DINAPUR/दानापुर',
        'MANER/मनेर',
        'NAUBATPUR/नौबतपुर'
      ],
      [
        'DHANARUA/धनरूआ',
        'MASAURHI/मसौढ़ी',
        'PUNPUN/पुनपुन'
      ],
      [
        'BIKRAM/बिक्रम',
        'DULHIN BAZAR/दुल्हिन बाजार',
        'PALIGANJ/पालीगंज'
      ],
      [
        'Daniyawan/दनियावां',
        'Fatuha/फतुहॉ',
        'Khusrupur/खुसरुपुर',
        'Patna Sadar/पटना सदर',
        'Patna Sadar - Didarganj/पटना सदर - दीदारगंज',
        'Patna Sadar - Patna City/पटना सदर - पटना सिटी'
      ],
      [
        'Patna Sadar/पटना सदर',
        'Patna Sadar - Patliputra/पटना सदर- पाटलिपुत्र',
        'Phulwari/फुलवारीशरीफ',
        'Sampatchak/संपतचक'
      ]
    ],
    [
      [
        'ARERAJ/अरेराज',
        'HARSIDHI/हरसिद्धि',
        'PAHARPUR/पहाड़पुर',
        'SANGRAMPUR/संग्रामपुर'
      ],
      [
        'CHAKIA (PIPRA)/चकिया(पिपरा',
        'KALYANPUR/कल्याणपुर',
        'KESARIA/केसरिया',
        'MEHSI/मेहसी'
      ],
      [
        'BANJARIYA/बंजरिया',
        'KOTWA/कोतवा',
        'MOTIHARI/मोतीहारी',
        'PIPRA KOTHI/पिपराकोठी',
        'SUGAULI/सुगौली',
        'TURKAULIA/तुरकौलिया'
      ],
      [
        'MADHUBAN/मधुबन',
        'PAKRIDAYAL/पकड़ीदयाल',
        'PATAHI/पताही',
        'PHENHARA/फेनहारा',
        'TETARIYA/तेतरिया'
      ],
      [
        'ADAPUR/अदापुर',
        'CHAWRADANO/चवरदानो',
        'RAMGARHWA/रामगढ़वा',
        'RAXAUL/रक्सौल'
      ],
      [
        'BANKATWA/बंकटवा',
        'CHIRAIYA/चिरैया',
        'DHAKA/ढाका',
        'GHORASAHAN/घोड़ासहन'
      ]
    ],
    [
      [
        'AMOUR/अमौर',
        'BAISA/बईसा',
        'BAISI/बईसी',
        'DAGRAUA/डगरुआ'
      ],
      [
        'BANMANKHI/बनमंखी'
      ],
      [
        'BARHARA/बड़हरा',
        'BHAWANIPUR/भवानीपुर',
        'DHAMDAHA/धमदाहा',
        'RUPOULI/रुपौली'
      ],
      [],
      [
        'JALALGARH/जलालगढ़',
        'KASBA/कस्बा',
        'KRITYANAND NAGAR/कृत्यानंद नगर',
        'PURNIA EAST/पुर्णिया पूर्वी',
        'SRINAGAR/श्रीनगर'
      ]
    ],
    [
      [
        'BIKRAMGANJ/बिक्रमगंज',
        'DAWATH/दावथ',
        'DINARA/दिनारा',
        'KARAKAT/काराकाट',
        'NASRIGANJ/नासरीगंज',
        'RAJPUR/राजपुर',
        'SANJHOULI/संझौली',
        'SURAJPURA/सूर्यपुरा'
      ],
      [
        'AKORHIGOLA/अकोढ़ीगोला',
        'DEHRI/डेहरी',
        'NAWHATTA/नौहट्टा',
        'ROHTAS/रोहतास',
        'TILOUTHU/तिलौथू'
      ],
      [
        'CHENARI/चेनारी',
        'KARGAHAR/करगहर',
        'KOCHAS/कोचस',
        'NOKHA/नोखा',
        'SASARAM/सासाराम',
        'SHEOSAGAR/शिवसागर'
      ]
    ],
    [
      [
        'KAHARA/कहरा',
        'MAHISHI/महिषी',
        'NAUHATTA/नवहट्टा',
        'PATARGHAT/पतरघट',
        'SATTAR KATTAIYA/सत्तरकटैया',
        'SONBARSA/सोनबरसा',
        'SOUR BAZAR/सौरबाजार'
      ],
      [
        'BANMA ITAHARI/बनमा इटहरी',
        'SALKHUA/सलखुआ',
        'SIMRI BAKHTIARPUR/सिमरीबख्तियारपुर'
      ]
    ],
    [
      [
        'DALSINGHSARAI/दलसिंह सराय',
        'UJIARPUR/उजियारपुर',
        'VIDYAPATI NAGAR/विद्यापतिनगर'
      ],
      [
        'MOHANPUR/मोहनपुर',
        'MOHIUDDINAGAR/मोहिउद्दीन नगर',
        'PATORI/पटोरी'
      ],
      [
        'BIBHUTIPUR/विभुतिपूर',
        'BITHAN/बिठान',
        'HASANPUR/हसनपुर',
        'ROSERA/रोसड़ा',
        'SHIVAJI NAGAR/शिवाजीनगर',
        'SINGHIA/सिंघिया'
      ],
      [
        'KALYANPUR/कल्याणपुर',
        'KHANPUR/खानपुर',
        'MORWA/मोरवा',
        'PUSA/पूसा',
        'SAMASTIPUR/समस्तीपुर',
        'SARAIRANJAN/सरायरंजन',
        'TAJPUR/ताजपुर',
        'WARISNAGAR/वारिसनगर'
      ]
    ],
    [
      [
        'AMNOUR/अमनौर',
        'ISUAPUR/इसुआपुर',
        'MARHAURAH/मढ़ौरा',
        'MASHRAKH/मशरख',
        'PANAPUR/पानापुर',
        'TARAIYA/तरैया'
      ],
      [
        'BANIAPUR/बनियापुर',
        'CHHAPRA/छपरा',
        'EKMA/इकमा',
        'GARKHA/गरखा',
        'JALALPUR/जलालपुर',
        'LAHLADPUR/लहलाद्पुर',
        'MAKER/मकेर',
        'MANJHI/मांझी',
        'NAGRA/नगरा',
        'PARSA/परसा',
        'REVELGANJ/रेविलगंज'
      ],
      [
        'DARIAPUR/दरियापुर',
        'DIGHWARA/दिघवारा',
        'SONEPUR/सोनपुर'
      ]
    ],
    [
      [
        'ARIARI/अरियरी',
        'BARBIGHA/बरबीघा',
        'CHEWARA/चेवाड़ा',
        'GHATKUSUMBHA/घाटकुसुम्भा',
        'SHEIKHPURA/शेखपुरा',
        'SHEKHOPUR SARAI/शेखोपुरसराय'
      ]
    ],
    [
      [
        'DUMARI KATSARI/डुमरी कटसरी',
        'PIPRAHI/पिपराही',
        'PURNAHIYA/पुरनहिया',
        'SHEOHAR/शिवहर',
        'TARIYANI/तरियानी'
      ]
    ],
    [
      [
        'BELSAND/बेलसंड',
        'PARSAUNI/परसौनी'
      ],
      [
        'BAJPATTI/बाजपट्टी',
        'BOKHRA/बोखरा',
        'CHORAUT/चोरौत',
        'NANPUR/नानपुर',
        'PUPRI/पूपरी',
        'SURSAND/सुरसंड'
      ],
      [
        'BAIRGANIA/बैरगनिया',
        'BATHANAHA/बथनाहा',
        'DUMRA/डुमरा',
        'MAJORGANJ/मजोरगंज',
        'PARIHAR/परिहार',
        'RIGA/रीगा',
        'RUNNISAIDPUR/रून्नी सैदपुर',
        'SONBARSA/सोनवर्षा',
        'SUPPI/सुप्पी'
      ]
    ],
    [
      [
        'BASANTPUR/बसंतपुर',
        'BHAGWANPUR HAT/भगवानपुर हाट',
        'DARAUNDHA/दरौन्दा',
        'GORIAKOTHI/गोरेयाकोठी',
        'LAKRI NABIGANJ/लकड़ी नबीगंज',
        'MAHARAJGANJ/महराजगंज'
      ],
      [
        'ANDAR/आन्दर',
        'BARHARIA/बड़हरिया',
        'DARAULI/दरौली',
        'GUTHANI/गुठनी',
        'HASAN PURA/हसनपुरा',
        'HUSSAINGANJ/हुसैनगंज',
        'MAIRWA/मैरवा',
        'NAUTAN/नौतन',
        'PACHRUKHI/पचरुखी',
        'RAGHUNATHPUR/रघुनाथपुर',
        'SISWAN/सिसवन',
        'SIWAN/सिवान सदर',
        'ZIRADEI/जीरादेई'
      ]
    ],
    [
      [
        'BASANTPUR/बसंतपुर',
        'PRATAPGANJ/प्रतापगंज',
        'RAGHOPUR/राघोपुर'
      ],
      [
        'MARAUNA/मरौना',
        'NIRMALI/निर्मली'
      ],
      [
        'KISHANPUR/किशनपुर',
        'PIPRA/पिपरा',
        'SARAIGARH BHAPTIYAHI/सरायगढ़ भाप्त',
        'SUPAUL/सुपौल'
      ],
      [
        'CHHATAPUR/छातापुर',
        'TRIBENIGANJ/त्रिवेनीगंज'
      ]
    ],
    [
      [
        'BHAGWANPUR/भगवानपुर',
        'BIDUPUR/वीदुपुर',
        'HAJIPUR/हाजीपुर',
        'LALGANJ/लालगंज',
        'PATEDHI BELSAR/पतेढ़ी बेलसर',
        'RAGHOPUR/राघोपुर',
        'VAISHALI/वैशाली'
      ],
      [
        'DESRI/देसरी',
        'MAHNAR/महनार',
        'SAHDEI BUZURG/सहदेई बुजुर्ग'
      ],
      [
        'CHEHRAKALA/चेहराकला',
        'GARAUL/गोरौल',
        'JANDAHA/जनदाहा',
        'MAHUA/महुआ',
        'PATEPUR/पातेपुर ',
        'RAJAPAKAR/राजापाकड़'
      ]
    ]
  ]
};

let stateIndex = 0;
let districtIndex = 0;

// State to Districts Rendering...
function addrPicker(value, index) {
  let name, option, district = districts[index],
    select = $('#district');

  select.innerHTML = '<option value="" disabled hidden selected>जिला / District</option>';
  stateIndex = index;

  for(name of district) {
    option = document.createElement('option');
    option.value = option.innerHTML = name;
    select.appendChild(option);
  }
}

// District to subDivision Rendering...
function subDivision(value, index) {
  let name, option, _sub_division = subDivisions[stateIndex][index],
  _police_stations = policeStations[stateIndex][index];
  select = $('#sub_division');

  select.innerHTML = '<option value="" disabled hidden selected>अनुमंडल / Sub-Division (optional)</option>';
  districtIndex = index;

  for(name of _sub_division) {
    option = document.createElement('option');
    option.value = option.innerHTML = name;
    select.appendChild(option);
  }

  select = $('#police_station');
  select.innerHTML = '<option value="" disabled hidden selected>थाना / Police Station</option>';

  for(name of _police_stations) {
    option = document.createElement('option');
    option.value = option.innerHTML = name;
    select.appendChild(option);
  }
}

// subDivision to Block Rendering...
function blockPicker(value, index) {
  let name, option, _blocks = blocks[stateIndex][districtIndex][index];
  select = $('#block');

  select.innerHTML = '<option value="" disabled hidden selected>प्रखंड / Block (optional)</option>';

  for(name of _blocks) {
    option = document.createElement('option');
    option.value = option.innerHTML = name;
    select.appendChild(option);
  }
}

// Caste Picker
function castePicker(value, index) {
  let caste, opt, option, elem = $('#caste');

  elem.innerHTML = '<option value="" disabled hidden selected>जाति / Caste</option>';
  caste = casts[index];

  for(option of caste) {
    opt = document.createElement('option');
    opt.value = opt.innerHTML = option;
    elem.appendChild(opt);
  }
}